import { strict as assert } from "node:assert";
import { evaluateElasticityConstruction, elasticityGeometryLabel, validateEvaluatedElasticityLabels, validateElasticityConstruction, type ElasticityEvaluationContext } from "../../src/compile/elasticityGeometry";
import { evaluateCalculusConstruction } from "../../src/compile/calculusGeometry";
import type { SceneConstruction, SceneDocument, SceneIssue } from "../../src/types";

const geometries = new Map<string, unknown>();
const context: ElasticityEvaluationContext = { number: Number, point() { throw new Error("no foreign metric reinterpretation"); }, geometry: (value) => typeof value === "string" ? geometries.get(value) : undefined };
const inputs = { model: "linear_elastic", youngModulus: 200, modulusUnit: "GPa", strainMin: -0.001, strainMax: 0.001, stressUnit: "MPa", strainScale: 10000, stressScale: 0.1, samples: 5 };
const profile = evaluateElasticityConstruction("elastic_profile", inputs, context)[0]!;
assert.equal(profile.kind, "path"); if (profile.kind !== "path") throw new Error("elastic law must retain its physical source and analytic callback");
assert.equal(profile.elasticProfile.youngModulusSI, 2e11); assert.deepEqual(profile.points[0], { x: -10, y: -20 }); assert.deepEqual(profile.points.at(-1), { x: 10, y: 20 });
geometries.set("profile", profile);
const state = evaluateElasticityConstruction("elastic_state", { profile: "profile", strain: 0.001, area: 100, areaUnit: "mm^2", length: 2, lengthUnit: "m", uniformBar: true }, context)[0]!;
assert.equal(state.kind, "point"); if (state.kind !== "point") throw new Error("elastic state must retain physical SI authority");
assert.equal(state.elasticState.stressSI, 2e8); assert.ok(Math.abs(state.elasticState.forceSI! - 20000) < 1e-9); assert.equal(state.elasticState.extensionSI, 0.002); assert.ok(Math.abs(state.elasticState.energyJ! - 20) < 1e-9);
const construction = { id: "make-state", operator: "elastic_state", inputs: { profile: "profile", strain: 0.001, area: 100, areaUnit: "mm^2", length: 2, lengthUnit: "m", uniformBar: true }, outputs: ["state"] };
const candidate: SceneDocument = { schemaVersion: "scene-document/v2", source: {}, quantities: [], entities: [{ id: "state", kind: "point", role: "elastic state", label: "F=2000 N" }], constructions: [construction], relations: [], assertions: [], annotations: [], requiredEntityIds: ["state"], revealGroups: [], teachingTimeline: [] };
const issues: SceneIssue[] = []; validateEvaluatedElasticityLabels(construction, 0, candidate, [state], issues);
assert.ok(issues.some((issue) => issue.severity === "fatal"), "computed load labels cannot contradict explicit stress and area");
const wrongUnit = structuredClone(candidate); wrongUnit.entities = [{ id: "profile", kind: "polyline", role: "linear constitutive law" }]; wrongUnit.constructions = [{ id: "make-profile", operator: "elastic_profile", inputs: { ...inputs, youngModulus: "E_mpa" }, outputs: ["profile"] }]; wrongUnit.quantities.push({ id: "E_mpa", value: 200000, unit: "MPa" });
const unitIssues: SceneIssue[] = []; validateElasticityConstruction(wrongUnit.constructions[0]!, 0, wrongUnit, new Map([["profile", wrongUnit.constructions[0]!]]), unitIssues);
assert.ok(unitIssues.some((issue) => issue.code === "invalid_elastic_profile_units"), "modulus quantity units cannot silently switch the declared source scale");
let checks = 9;
function check(condition: unknown, message: string): void { checks++; assert.ok(condition, message); }
function close(actual: number, expected: number, message: string, tolerance = 1e-10): void { checks++; assert.ok(Math.abs(actual - expected) <= tolerance * Math.max(Math.abs(expected), 1), `${message}: ${actual} != ${expected}`); }
function reject(operator: string, values: Record<string, unknown>): void { checks++; assert.throws(() => evaluateElasticityConstruction(operator, values, context)); }
const stateInputs = construction.inputs;
reject("elastic_profile", { ...inputs, modulusUnit: "mPa" });
reject("elastic_profile", { ...inputs, stressUnit: "mPa" });
reject("elastic_profile", { ...inputs, modulusUnit: "MPa", youngModulus: { value: 200000, unit: "mPa" } });
for (const [strain, stress, force, extension, energy] of [[-0.001, -2e8, -20000, -0.002, 20], [-0.0005, -1e8, -10000, -0.001, 5], [0, 0, 0, 0, 0], [0.00025, 5e7, 5000, 0.0005, 1.25], [0.001, 2e8, 20000, 0.002, 20]]) {
  const value = evaluateElasticityConstruction("elastic_state", { ...stateInputs, strain }, context)[0]!; if (value.kind !== "point") throw new Error("exact elastic state must be a point"); const physical = value.elasticState;
  close(physical.stressSI, stress!, "worked-example signed stress"); close(physical.forceSI!, force!, "worked-example signed axial load"); close(physical.extensionSI!, extension!, "worked-example signed extension/compression"); close(physical.energyJ!, energy!, "worked-example nonnegative strain energy"); close(physical.forceSI! / physical.areaSI!, physical.stressSI, "load divided by area recovers independently given constitutive stress"); close(physical.extensionSI! / physical.lengthSI!, strain!, "extension divided by length recovers source strain"); close(physical.energyJ!, physical.forceSI! * physical.extensionSI! / 2, "linear loading work equals triangular load-extension area");
  assert.deepEqual(value.calculusAnchor, { curveId: "profile", parameter: strain }); assert.deepEqual(value.point, profile.sampledCurve.evaluate(strain!)); checks += 2;
  close(profile.sampledCurve.derivative(strain!).y / 0.1 * 1e6, 2e11, "physical sigma'=E recovered independently from display derivative units");
}
for (const [modulusUnit, youngModulus] of [["Pa", 2e11], ["kPa", 2e8], ["MPa", 2e5], ["GPa", 200]] as const) for (const [stressUnit, stressScale] of [["Pa", 1e-7], ["kPa", 1e-4], ["MPa", 0.1], ["GPa", 100]] as const) {
  const converted = evaluateElasticityConstruction("elastic_profile", { ...inputs, modulusUnit, youngModulus, stressUnit, stressScale, origin: [19, -31] }, context)[0]!; if (converted.kind !== "path") throw new Error("converted modulus/stress source requires an analytic graph");
  close(converted.elasticProfile.youngModulusSI, 2e11, "SI modulus independent of source units"); converted.points.forEach((point, index) => { close(point.x - 19, -10 + 5 * index, "translated strain display invariance"); close(point.y + 31, -20 + 10 * index, "translated stress display invariance"); });
}
for (const [area, areaUnit, length, lengthUnit] of [[0.0001, "m^2", 2, "m"], [1, "cm^2", 200, "cm"], [100, "mm^2", 2000, "mm"]] as const) {
  const value = evaluateElasticityConstruction("elastic_state", { ...stateInputs, area, areaUnit, length, lengthUnit }, context)[0]!; if (value.kind !== "point") throw new Error("mixed bar dimensions require a physical state"); close(value.elasticState.forceSI!, 20000, "area-unit invariant axial force"); close(value.elasticState.extensionSI!, 0.002, "length-unit invariant extension"); close(value.elasticState.energyJ!, 20, "mixed-unit invariant strain energy");
}
const stressOnly = evaluateElasticityConstruction("elastic_state", { profile: "profile", strain: 0.001 }, context)[0]!; if (stressOnly.kind !== "point") throw new Error("stress-only state must remain a point"); check(stressOnly.elasticState.forceSI === undefined && stressOnly.elasticState.extensionSI === undefined && stressOnly.elasticState.energyJ === undefined && !stressOnly.elasticState.uniformBar, "missing physical dimensions cannot imply load, extension, or energy");
const derivative = evaluateCalculusConstruction("curve_derivative", { curve: "profile", at: 0.0005, parameterScale: 0.0001 }, context)[0]!; if (derivative.kind !== "path") throw new Error("positive modulus yields an exact nonzero display derivative"); close(derivative.points[1]!.x - derivative.points[0]!.x, 1, "dimensionless strain parameter scaling"); close(derivative.points[1]!.y - derivative.points[0]!.y, 2, "logical derivative distinct from physical modulus");
for (const [key, value] of [["model", undefined], ["model", "plastic"], ["youngModulus", 0], ["youngModulus", -1], ["youngModulus", "1e-400"], ["modulusUnit", "N"], ["strainMin", 0.001], ["strainMax", Infinity], ["strainMax", 1001], ["strainScale", 0], ["stressScale", 0], ["stressScale", 1e-200], ["strainScale", 1e-200], ["samples", 1], ["samples", 514], ["samples", 4.5], ["origin", "physicalPoint"], ["yieldStrength", 1]] as const) reject("elastic_profile", { ...inputs, [key]: value });
for (const overrides of [{ youngModulus: { value: 200, unit: "MPa" } }, { strainMin: { value: -0.001, unit: "%" } }, { strainScale: { value: 10000, unit: "m" } }, { youngModulus: 1e12 }, { origin: [1e12, 1e12], strainScale: 0.01, stressScale: 1e-6 }, { youngModulus: 1e-200, strainMin: 1e-200, strainMax: 2e-200 }]) reject("elastic_profile", { ...inputs, ...overrides });
for (const overrides of [{ strain: 0.01 }, { strain: NaN }, { strain: "1e-400" }, { strain: { value: 0.001, unit: "m" } }, { area: 0 }, { length: 0 }, { uniformBar: false }, { uniformBar: undefined }, { areaUnit: undefined }, { lengthUnit: undefined }, { area: { value: 100, unit: "cm^2" } }, { length: { value: 2, unit: "cm" } }, { area: 1e-300, length: 1e-300 }, { force: 1 }]) reject("elastic_state", { ...stateInputs, ...overrides });
geometries.set("tampered", { ...profile, elasticProfile: { ...profile.elasticProfile, youngModulusSI: 1 } }); reject("elastic_state", { ...stateInputs, profile: "tampered" });
geometries.set("projected", { ...profile, spacePlane: {} }); reject("elastic_state", { ...stateInputs, profile: "projected" });
const mathematical = evaluateElasticityConstruction("elastic_profile", { ...inputs, strainMin: -2, strainMax: 2, strainScale: 1, stressScale: 1e-6 }, context)[0]!; geometries.set("mathematical", mathematical); reject("elastic_state", { profile: "mathematical", strain: -1, length: 1, lengthUnit: "m", uniformBar: true });
assert.equal(elasticityGeometryLabel(profile), "sigma=E*epsilon"); assert.equal(elasticityGeometryLabel(state), "sigma(epsilon)"); assert.equal(elasticityGeometryLabel(state, "F=20 kN"), "F=20 kN"); checks += 3;
function documentFor(): SceneDocument {
  const constructions: SceneConstruction[] = [{ id: "make-profile", operator: "elastic_profile", inputs: { ...inputs }, outputs: ["profile"] }, { id: "make-state", operator: "elastic_state", inputs: { ...stateInputs, strain: { value: "strain", unit: "1" } }, outputs: ["state"] }];
  return { schemaVersion: "scene-document/v2", source: { question: "Show the explicitly specified linear elastic constitutive law and uniform bar state." }, visualDecision: { mode: "scene", reason: "explicit source-defined linear elasticity" }, quantities: [{ id: "strain", value: 0.001, unit: "1" }], entities: [{ id: "profile", kind: "polyline", role: "linear elastic stress-strain law" }, { id: "state", kind: "point", role: "exact uniform bar elastic state" }], constructions, relations: [], assertions: [], annotations: [], requiredEntityIds: ["profile", "state"], revealGroups: [{ id: "setup", entityIds: ["profile", "state"], dependsOn: [], narrationCue: "show linear elastic law" }], teachingTimeline: [{ id: "show", action: "reveal", targetId: "setup", dependsOn: [], narrationIntent: "show source-defined elasticity state" }] };
}
function issuesFor(scene: SceneDocument): SceneIssue[] { const found: SceneIssue[] = []; const map = new Map(scene.constructions.flatMap((source) => source.outputs.map((id) => [id, source] as const))); scene.constructions.forEach((source, index) => validateElasticityConstruction(source, index, scene, map, found)); return found; }
function rejectDocument(scene: SceneDocument, code: string): void { check(issuesFor(scene).some((issue) => issue.code === code && issue.severity === "fatal"), `expected ${code}: ${JSON.stringify(issuesFor(scene))}`); }
assert.deepEqual(issuesFor(documentFor()), []); checks++;
for (const [index, label, valid] of [[0, "sigma=E*epsilon", true], [0, "E=200 GPa", true], [0, "E=200 MPa", false], [1, "sigma=200 MPa", true], [1, "sigma=2e8 Pa", true], [1, "sigma=20 MPa", false], [1, "F=20 kN", true], [1, "F=20000 N", true], [1, "F=2000 N", false], [1, "deltaL=2 mm", true], [1, "deltaL=-2 mm", false], [1, "U=20 J", true], [1, "U=-20 J", false]] as const) { const scene = documentFor(); scene.entities[index]!.label = label; if (valid) { assert.deepEqual(issuesFor(scene), []); checks++; } else rejectDocument(scene, `invalid_${scene.constructions[index]!.operator}_label`); }
for (const [target, value, unit, text, valid] of [["profile", 200, "GPa", "E", true], ["state", 200, "MPa", undefined, true], ["state", 20, "kN", "F", true], ["state", 2, "mm", "deltaL", true], ["state", 0.02, "kJ", "U", true], ["state", 20, "J", undefined, true], ["state", 20, "kJ", "U", false], ["state", -2, "mm", "deltaL", false]] as const) { const scene = documentFor(); scene.quantities.push({ id: "result", value, unit }); scene.annotations.push({ id: "result-label", kind: "label", targetIds: [target], text, quantityId: "result" }); if (valid) { assert.deepEqual(issuesFor(scene), []); checks++; } else rejectDocument(scene, `invalid_${target === "profile" ? "elastic_profile" : "elastic_state"}_label`); }
const absentArea = documentFor(); absentArea.constructions[1]!.inputs = { profile: "profile", strain: 0.001 }; absentArea.entities[1]!.label = "F=0 N"; rejectDocument(absentArea, "invalid_elastic_state_label");
const mismatched = documentFor(); mismatched.quantities.push({ id: "modulus", value: 200000, unit: "MPa" }); mismatched.constructions[0]!.inputs.youngModulus = "modulus"; rejectDocument(mismatched, "invalid_elastic_profile_units");
const wrongStrainUnit = documentFor(); wrongStrainUnit.quantities[0]!.unit = "m"; rejectDocument(wrongStrainUnit, "invalid_elastic_state_units");
const stale = documentFor(); stale.entities[1]!.label = "F=999 N"; rejectDocument(stale, "invalid_elastic_state_label");
const noModel = documentFor(); delete noModel.constructions[0]!.inputs.model; rejectDocument(noModel, "invalid_elastic_profile_model");
const noAssumption = documentFor(); delete noAssumption.constructions[1]!.inputs.uniformBar; rejectDocument(noAssumption, "invalid_elastic_state_uniformBar");
const cyclic = documentFor(); cyclic.quantities.push({ id: "x", value: "y" }, { id: "y", value: "x" }); cyclic.constructions[0]!.inputs.youngModulus = "x"; check(issuesFor(cyclic).some((issue) => issue.severity === "fatal"), "cyclic modulus quantity authority rejects");
const zero = documentFor(); zero.quantities[0]!.value = 0; assert.deepEqual(issuesFor(zero), []); checks++;
const falseZero = structuredClone(zero); falseZero.quantities.push({ id: "unresolved-extension", value: 1e-323, unit: "cm" }); falseZero.annotations.push({ id: "false-zero", kind: "label", targetIds: ["state"], text: "deltaL", quantityId: "unresolved-extension" }); rejectDocument(falseZero, "invalid_elastic_state_label");
const wrongOutputs = documentFor(); wrongOutputs.constructions[0]!.outputs.push("state"); rejectDocument(wrongOutputs, "invalid_elastic_profile_outputs");
if (!process.argv.includes("--unit-only")) {
  const { compileSceneDocument, validateSceneDocument, isSupportedSceneOperator } = await import("../../src/index");
  function compiled(scene: SceneDocument) { const before = JSON.stringify(scene); const validated = validateSceneDocument(scene); assert.ok(validated.document, `elastic validation failed: ${JSON.stringify(validated.report.issues)}`); const result = compileSceneDocument(validated.document); assert.ok(result.ok && result.renderScene, `elastic compile failed: ${JSON.stringify(result.report.issues)}`); check(JSON.stringify(scene) === before, "elastic compilation does not mutate source document"); check(result.renderScene.primitives.every((primitive) => primitive.points.every((point) => Number.isFinite(point.x) && Number.isFinite(point.y))), "elastic ink remains finite"); return result.renderScene.primitives; }
  for (const operator of ["elastic_profile", "elastic_state"]) check(isSupportedSceneOperator(operator), "elastic derivation has executable capability");
  const live = documentFor(); live.constructions.reverse(); live.assertions.push({ id: "exact-elastic-state", predicate: "incident", entities: ["state", "profile"], severity: "fatal", tolerance: 1e-8 }); const ink = compiled(live); check(ink.some((primitive) => primitive.entityId === "profile" && primitive.text === "sigma=E*epsilon"), "initial elastic graph shows its source law"); check(!ink.some((primitive) => /^(?:sigma|F|deltaL|U)=[+-]?\d/.test(primitive.text ?? "")), "computed answers are absent unless requested"); compiled(zero);
  const compression = documentFor(); compression.quantities[0]!.value = -0.001; compiled(compression);
  const requested = documentFor(); requested.entities[1]!.label = "U=20 J"; check(compiled(requested).some((primitive) => primitive.text === "U=20 J"), "explicit verified energy requests preserve source authority");
  const bound = documentFor(); bound.quantities.push({ id: "source-E", value: "200", unit: "GPa" }, { id: "source-area", value: { value: "100", unit: "mm^2" }, unit: "mm^2" }, { id: "source-length", value: 2, unit: "m" }); bound.constructions[0]!.inputs.youngModulus = { value: "source-E", unit: "GPa" }; bound.constructions[1]!.inputs.area = "source-area"; bound.constructions[1]!.inputs.length = { value: "source-length", unit: "m" }; bound.entities[1]!.label = "U=20 J"; bound.constructions.reverse(); check(compiled(bound).some((primitive) => primitive.text === "U=20 J"), "nested quantity and source-unit bindings preserve independently computed uniform-bar energy");
  const calculus = documentFor(); calculus.quantities.push({ id: "at-strain", value: 0.0005, unit: "1" }, { id: "parameter-scale", value: 0.0001, unit: "1" });
  for (const [id, kind, operator, values] of [["anchor", "point", "curve_anchor", { curve: "profile", at: { value: 0.00025, unit: "1" } }], ["derivative", "vector", "curve_derivative", { curve: "profile", at: "at-strain", parameterScale: "parameter-scale" }], ["tangent", "line", "tangent_line", { curve: "profile", at: "at-strain", span: 15 }], ["normal", "line", "normal_line", { curve: "profile", at: "at-strain", span: 15 }], ["secant", "line", "curve_secant", { curve: "profile", first: -0.0005, second: 0.00075, span: 35 }]] as const) { calculus.entities.push({ id, kind, role: "exact elasticity analytic composition", ...(id === "derivative" ? { label: "dSigma" } : {}) }); calculus.constructions.push({ id: `make-${id}`, operator, inputs: values, outputs: [id] }); calculus.requiredEntityIds.push(id); calculus.revealGroups[0]!.entityIds.push(id); }
  calculus.assertions.push({ id: "exact-anchor", predicate: "incident", entities: ["anchor", "profile"], severity: "fatal" }, { id: "exact-tangent", predicate: "parallel", entities: ["tangent", "derivative"], severity: "fatal", tolerance: 1e-8 }, { id: "exact-normal", predicate: "perpendicular", entities: ["normal", "derivative"], severity: "fatal", tolerance: 1e-8 }, { id: "linear-law-secant", predicate: "parallel", entities: ["secant", "tangent"], severity: "fatal", tolerance: 1e-8 }); calculus.constructions.reverse(); compiled(calculus);
  const falseDisplayClaim = structuredClone(calculus); falseDisplayClaim.entities.find((entity) => entity.id === "derivative")!.label = "E=2 Pa";
  const wrongParameter = structuredClone(calculus); wrongParameter.quantities.find((quantity) => quantity.id === "parameter-scale")!.unit = "m";
  const endpoint = structuredClone(calculus); endpoint.constructions.find((source) => source.operator === "tangent_line")!.inputs.at = 0.001;
  const underflow = documentFor(); underflow.constructions[0]!.inputs.stressScale = 1e-200;
  const wrongPrefix = documentFor(); wrongPrefix.constructions[0]!.inputs.modulusUnit = "mPa";
  const quantityPrefix = documentFor(); quantityPrefix.quantities.push({ id: "wrong-prefix-modulus", value: 200000, unit: "mPa" }); quantityPrefix.constructions[0]!.inputs.modulusUnit = "MPa"; quantityPrefix.constructions[0]!.inputs.youngModulus = "wrong-prefix-modulus";
  const labelPrefix = documentFor(); labelPrefix.entities[1]!.label = "sigma=200 mPa";
  for (const invalid of [absentArea, mismatched, wrongStrainUnit, stale, noModel, noAssumption, cyclic, falseZero, wrongOutputs, falseDisplayClaim, wrongParameter, endpoint, underflow, wrongPrefix, quantityPrefix, labelPrefix]) { const result = compileSceneDocument(invalid); check(!result.ok && result.renderScene === null, `invalid elastic candidate cannot partially render: ${JSON.stringify(result.report.issues)}`); }
}
console.log(`elasticity operators verified: ${checks} independent constitutive, load/extension/energy, unit, calculus, and atomic rejection checks`);
