import { strict as assert } from "node:assert";
import { evaluateHarmonicMotionConstruction, harmonicMotionGeometryLabel, validateEvaluatedHarmonicMotionLabels, validateHarmonicMotionConstruction, type HarmonicMotionEvaluationContext } from "../../src/compile/harmonicMotionGeometry";
import { evaluateCalculusConstruction } from "../../src/compile/calculusGeometry";
import type { SceneConstruction, SceneDocument, SceneIssue } from "../../src/types";

const geometry = new Map<string, unknown>();
const context: HarmonicMotionEvaluationContext = { number: Number, point() { throw new Error("no source geometry reinterpretation"); }, geometry: (value) => typeof value === "string" ? geometry.get(value) : undefined };
const inputs = { amplitude: 2, equilibrium: 3, angularFrequency: 4, phase: 0, phaseUnit: "rad", tMin: 0, tMax: Math.PI / 2, lengthUnit: "cm", timeUnit: "s", frequencyUnit: "rad/s", quantity: "position", timeScale: 10, ordinateScale: 2 };
const motion = evaluateHarmonicMotionConstruction("harmonic_motion", inputs, context)[0]!;
assert.equal(motion.kind, "path"); if (motion.kind !== "path") throw new Error("time graph must retain source metadata");
assert.deepEqual(motion.sampledCurve.evaluate(0), { x: 0, y: 10 });
assert.equal(motion.harmonicMotion.amplitudeSI, 0.02);
geometry.set("motion", motion);
const state = evaluateHarmonicMotionConstruction("harmonic_state", { motion: "motion", time: Math.PI / 8 }, context)[0]!;
assert.equal(state.kind, "point"); if (state.kind !== "point") throw new Error("harmonic state must retain exact parameter authority");
assert.ok(Math.abs(state.harmonicState.positionSI - 0.03) < 1e-12);
assert.ok(Math.abs(state.harmonicState.velocitySI + 0.08) < 1e-12);
assert.ok(Math.abs(state.harmonicState.accelerationSI) < 1e-12);
const construction = { id: "make-motion", operator: "harmonic_motion", inputs, outputs: ["motion"] };
const candidate: SceneDocument = { schemaVersion: "scene-document/v2", source: {}, quantities: [], entities: [{ id: "motion", kind: "polyline", role: "explicit harmonic source" }], constructions: [construction], relations: [], assertions: [], annotations: [{ id: "false-frequency", kind: "label", targetIds: ["motion"], text: "omega=999 rad/s" }], requiredEntityIds: ["motion"], revealGroups: [], teachingTimeline: [] };
const issues: SceneIssue[] = []; validateEvaluatedHarmonicMotionLabels(construction, 0, candidate, [motion], issues);
assert.ok(issues.some((issue) => issue.severity === "fatal"), "source labels cannot contradict the explicit harmonic frequency");
const wrongUnit = structuredClone(candidate); wrongUnit.annotations = []; wrongUnit.quantities.push({ id: "A_si", value: 0.02, unit: "m" }); wrongUnit.constructions[0]!.inputs.amplitude = "A_si";
const unitIssues: SceneIssue[] = []; validateHarmonicMotionConstruction(wrongUnit.constructions[0]!, 0, wrongUnit, new Map([["motion", wrongUnit.constructions[0]!]]), unitIssues);
assert.ok(unitIssues.some((issue) => issue.severity === "fatal"), "quantity amplitude cannot change its declared source unit scale");
let checks = 10;
function check(condition: unknown, message: string): void { checks++; assert.ok(condition, message); }
function close(actual: number, expected: number, message: string, tolerance = 1e-10): void { checks++; assert.ok(Math.abs(actual - expected) <= tolerance * Math.max(Math.abs(expected), 1), `${message}: ${actual} != ${expected}`); }
function reject(operator: string, values: Record<string, unknown>): void { checks++; assert.throws(() => evaluateHarmonicMotionConstruction(operator, values, context)); }
reject("harmonic_motion", { ...inputs, lengthUnit: "Mm" });
for (const [time, q, v, a] of [[0, 5, 0, -32], [Math.PI / 8, 3, -8, 0], [Math.PI / 4, 1, 0, 32], [3 * Math.PI / 8, 3, 8, 0], [Math.PI / 2, 5, 0, -32]]) {
  const value = evaluateHarmonicMotionConstruction("harmonic_state", { motion: "motion", time }, context)[0]!; if (value.kind !== "point") throw new Error("source state must be a point"); const state = value.harmonicState;
  close(state.positionSI, q! / 100, "worked-example position at phase landmarks"); close(state.velocitySI, v! / 100, "worked-example velocity quadrature"); close(state.accelerationSI, a! / 100, "worked-example restoring acceleration");
  close(state.accelerationSI, -16 * state.displacementSI, "SHM differential law relative to equilibrium"); close(state.velocitySI ** 2 + 16 * state.displacementSI ** 2, 0.0064, "phase-independent quadratic energy invariant");
  assert.deepEqual(value.calculusAnchor, { curveId: "motion", parameter: time }); assert.deepEqual(value.point, motion.sampledCurve.evaluate(time!)); checks += 2;
}
for (const quantity of ["position", "velocity", "acceleration"] as const) {
  const graph = evaluateHarmonicMotionConstruction("harmonic_motion", { ...inputs, quantity }, context)[0]!; if (graph.kind !== "path") throw new Error("each observable requires a time graph"); geometry.set(quantity, graph);
  const slope = graph.sampledCurve.derivative(Math.PI / 8); close(slope.x, 10, "display derivative retains source-time horizontal scale"); close(slope.y, quantity === "position" ? -16 : quantity === "velocity" ? 0 : 256, "independent analytic derivative at quadrature");
  const scaled = evaluateCalculusConstruction("curve_derivative", { curve: quantity, at: Math.PI / 8, parameterScale: 0.25 }, context)[0]!; if (scaled.kind !== "path") throw new Error("source time remains a nonzero horizontal derivative"); close(scaled.points[1]!.x - scaled.points[0]!.x, 2.5, "calculus source-time parameter scaling"); close(scaled.points[1]!.y - scaled.points[0]!.y, slope.y * 0.25, "calculus derivative uses display ordinate, not physical SI");
  for (const frequencyUnit of ["rad/s", "rad/ms"]) {
    const converted = evaluateHarmonicMotionConstruction("harmonic_motion", { ...inputs, quantity, amplitude: 0.02, equilibrium: 0.03, lengthUnit: "m", timeUnit: "ms", frequencyUnit, angularFrequency: frequencyUnit === "rad/s" ? 4 : 0.004, tMax: 1000 * Math.PI / 2, timeScale: 0.01, ordinateScale: quantity === "position" ? 200 : quantity === "velocity" ? 2e5 : 2e8 }, context)[0]!;
    if (converted.kind !== "path") throw new Error("converted physical source must remain analytic"); geometry.set("converted", converted); const convertedState = evaluateHarmonicMotionConstruction("harmonic_state", { motion: "converted", time: 1000 * Math.PI / 8 }, context)[0]!; if (convertedState.kind !== "point") throw new Error("converted state must be a point");
    close(convertedState.harmonicState.positionSI, 0.03, "mixed source units preserve SI position"); close(convertedState.harmonicState.velocitySI, -0.08, "mixed source units preserve SI velocity"); close(convertedState.harmonicState.accelerationSI, 0, "mixed source units preserve SI acceleration");
    close(converted.sampledCurve.evaluate(1000 * Math.PI / 8).x, graph.sampledCurve.evaluate(Math.PI / 8).x, "display time reparameterization invariance"); close(converted.sampledCurve.evaluate(1000 * Math.PI / 8).y, graph.sampledCurve.evaluate(Math.PI / 8).y, "display ordinate reparameterization invariance");
  }
  const constant = evaluateHarmonicMotionConstruction("harmonic_motion", { ...inputs, quantity, amplitude: 0, samples: 2 }, context)[0]!; if (constant.kind !== "path") throw new Error("zero amplitude is a constant graph, not a point"); check(constant.harmonicMotion.zeroAmplitude && constant.points.every((point) => point.y === (quantity === "position" ? 6 : 0)), "source-certified zero amplitude has the exact observable baseline"); assert.deepEqual(constant.sampledCurve.derivative(0), { x: 10, y: 0 }); checks++;
  const translated = evaluateHarmonicMotionConstruction("harmonic_motion", { ...inputs, quantity, origin: [19, -31] }, context)[0]!; if (translated.kind !== "path") throw new Error("translated motion must preserve the observable"); close(translated.sampledCurve.evaluate(Math.PI / 4).y + 31, graph.sampledCurve.evaluate(Math.PI / 4).y, "translation retains harmonic zero crossings within source oscillation precision");
  assert.equal(harmonicMotionGeometryLabel(graph), quantity === "position" ? "q(t)" : quantity === "velocity" ? "v(t)" : "a(t)"); checks++;
}
for (const [key, value] of [["amplitude", -1], ["amplitude", "1e-400"], ["equilibrium", undefined], ["angularFrequency", 0], ["angularFrequency", undefined], ["angularFrequency", Infinity], ["phase", undefined], ["phaseUnit", "deg"], ["frequencyUnit", "Hz"], ["lengthUnit", "s"], ["timeUnit", "m"], ["quantity", "energy"], ["tMax", 0], ["tMin", Math.PI / 2], ["timeScale", 0], ["ordinateScale", 0], ["samples", 2], ["samples", 2050], ["samples", 33.5], ["origin", "worldPoint"], ["mass", 1]] as const) reject("harmonic_motion", { ...inputs, [key]: value });
for (const overrides of [{ amplitude: { value: 2, unit: "m" } }, { angularFrequency: { value: 4, unit: "Hz" } }, { phase: { value: 0, unit: "deg" } }, { timeScale: { value: 10, unit: "s" } }, { origin: [{ value: 0, unit: "cm" }, 0] }, { amplitude: 1e-200, ordinateScale: 1e-200 }, { angularFrequency: 1e-200, amplitude: 1e-200 }, { equilibrium: 1e12, amplitude: 1e-8 }, { equilibrium: 1e12, amplitude: 1, ordinateScale: 0.1 }, { origin: [1e12, 1e12], timeScale: 1e-5, ordinateScale: 1e-5 }, { angularFrequency: 1e6, tMax: 100 }, { angularFrequency: 1e-200, tMax: 1e-200 }, { phase: -4, tMin: 1 + Number.EPSILON, tMax: 2 }, { equilibrium: 2, samples: 33 }]) reject("harmonic_motion", { ...inputs, ...overrides });
for (const time of [-1, Math.PI / 2 + 0.01, NaN, undefined, { value: 1, unit: "ms" }]) reject("harmonic_state", { motion: "motion", time });
reject("harmonic_motion", { ...inputs, quantity: "acceleration", equilibrium: 0, amplitude: 1e-12, angularFrequency: 1e12, tMax: 1e-11, timeScale: 1e9, ordinateScale: 1e-12 });
geometry.set("foreign", { kind: "path", points: motion.points }); reject("harmonic_state", { motion: "foreign", time: 0 });
geometry.set("protected", { ...motion, spaceLine: {} }); reject("harmonic_state", { motion: "protected", time: 0 });
geometry.set("tampered", { ...motion, harmonicMotion: { ...motion.harmonicMotion, angularFrequencySI: 1 } }); reject("harmonic_state", { motion: "tampered", time: 0 });
function documentFor(quantity: "position" | "velocity" | "acceleration" = "position"): SceneDocument {
  const constructions: SceneConstruction[] = [{ id: "make-motion", operator: "harmonic_motion", inputs: { ...inputs, quantity }, outputs: ["motion"] }, { id: "make-state", operator: "harmonic_state", inputs: { motion: "motion", time: { value: "time", unit: "s" } }, outputs: ["state"] }];
  return { schemaVersion: "scene-document/v2", source: { question: "Show the explicitly given simple harmonic time graph." }, visualDecision: { mode: "scene", reason: "explicit source-defined harmonic motion" }, quantities: [{ id: "time", value: Math.PI / 8, unit: "s" }], entities: [{ id: "motion", kind: "polyline", role: "harmonic observable time graph" }, { id: "state", kind: "point", role: "exact harmonic state" }], constructions, relations: [], assertions: [], annotations: [], requiredEntityIds: ["motion", "state"], revealGroups: [{ id: "setup", entityIds: ["motion", "state"], dependsOn: [], narrationCue: "show verified harmonic motion" }], teachingTimeline: [{ id: "show", action: "reveal", targetId: "setup", dependsOn: [], narrationIntent: "show source-defined harmonic observable" }] };
}
function issuesFor(scene: SceneDocument): SceneIssue[] { const found: SceneIssue[] = []; const map = new Map(scene.constructions.flatMap((source) => source.outputs.map((id) => [id, source] as const))); scene.constructions.forEach((source, index) => validateHarmonicMotionConstruction(source, index, scene, map, found)); return found; }
function rejectDocument(scene: SceneDocument, code: string): void { check(issuesFor(scene).some((issue) => issue.code === code && issue.severity === "fatal"), `expected ${code}: ${JSON.stringify(issuesFor(scene))}`); }
for (const quantity of ["position", "velocity", "acceleration"] as const) { assert.deepEqual(issuesFor(documentFor(quantity)), []); checks++; }
for (const [index, label, valid] of [[0, "q(t)", true], [0, "A=2 cm", true], [0, "q0=0.03 m", true], [0, "omega=4 rad/s", true], [0, "omega=4 Hz", false], [0, "A=2 m", false], [1, "q=3 cm", true], [1, "v=-8 cm/s", true], [1, "v=-8 m/s", false], [1, "a=0 cm/s^2", false], [1, "t=392.7 ms", true]] as const) { const scene = documentFor(); scene.entities[index]!.label = label; if (valid) { assert.deepEqual(issuesFor(scene), []); checks++; } else rejectDocument(scene, `invalid_${scene.constructions[index]!.operator}_label`); }
for (const [target, value, unit, text, valid] of [["motion", 0.02, "m", "A", true], ["motion", 4, "rad/s", undefined, true], ["motion", 2, "cm", undefined, false], ["state", -0.08, "m/s", "v", true], ["state", 3, "cm", "q", true], ["state", 999, "m/s", "v", false], ["state", -0.08, "m/s^2", "v", false]] as const) { const scene = documentFor(); scene.quantities.push({ id: "result", value, unit }); scene.annotations.push({ id: "result-label", kind: "label", targetIds: [target], text, quantityId: "result" }); if (valid) { assert.deepEqual(issuesFor(scene), []); checks++; } else rejectDocument(scene, `invalid_${target === "state" ? "harmonic_state" : "harmonic_motion"}_label`); }
const sourceUnitMismatch = documentFor(); sourceUnitMismatch.quantities.push({ id: "amplitude", value: 0.02, unit: "m" }); sourceUnitMismatch.constructions[0]!.inputs.amplitude = "amplitude"; rejectDocument(sourceUnitMismatch, "invalid_harmonic_motion_units");
const timeUnitMismatch = documentFor(); timeUnitMismatch.quantities[0]!.unit = "ms"; rejectDocument(timeUnitMismatch, "invalid_harmonic_state_units");
const wrongLabel = documentFor(); wrongLabel.entities[1]!.label = "v=999 m/s"; rejectDocument(wrongLabel, "invalid_harmonic_state_label");
const zeroAmplitudeUnderflow = documentFor(); zeroAmplitudeUnderflow.quantities.push({ id: "unresolved-A", value: "1e-400", unit: "cm" }); zeroAmplitudeUnderflow.constructions[0]!.inputs.amplitude = "unresolved-A"; rejectDocument(zeroAmplitudeUnderflow, "invalid_harmonic_motion_quantity");
const cycle = documentFor(); cycle.quantities.push({ id: "a", value: "b" }, { id: "b", value: "a" }); cycle.constructions[0]!.inputs.amplitude = "a"; check(issuesFor(cycle).some((issue) => issue.severity === "fatal"), "cyclic numeric quantity authority rejects");
const wrongOutputs = documentFor(); wrongOutputs.constructions[0]!.outputs.push("state"); rejectDocument(wrongOutputs, "invalid_harmonic_motion_outputs");
const wrongKind = documentFor(); wrongKind.entities[0]!.kind = "point"; rejectDocument(wrongKind, "invalid_harmonic_motion_output_kind");
const megaMeter = documentFor(); megaMeter.constructions[0]!.inputs.lengthUnit = "Mm"; rejectDocument(megaMeter, "invalid_harmonic_motion_units");
if (!process.argv.includes("--unit-only")) {
  const { compileSceneDocument, validateSceneDocument, isSupportedSceneOperator } = await import("../../src/index");
  function compiled(scene: SceneDocument) { const validated = validateSceneDocument(scene); assert.ok(validated.document, `harmonic validation failed: ${JSON.stringify(validated.report.issues)}`); const result = compileSceneDocument(validated.document); assert.ok(result.ok && result.renderScene, `harmonic compile failed: ${JSON.stringify(result.report.issues)}`); check(result.renderScene.primitives.every((primitive) => primitive.points.every((point) => Number.isFinite(point.x) && Number.isFinite(point.y))), "harmonic display ink remains finite"); return result.renderScene.primitives; }
  for (const operator of ["harmonic_motion", "harmonic_state"]) check(isSupportedSceneOperator(operator), "harmonic operator has executable capability");
  for (const quantity of ["position", "velocity", "acceleration"] as const) { const scene = documentFor(quantity); scene.constructions.reverse(); scene.assertions.push({ id: "exact-harmonic-state", predicate: "incident", entities: ["state", "motion"], severity: "fatal", tolerance: 1e-8 }); const ink = compiled(scene); check(ink.some((primitive) => primitive.entityId === "motion" && primitive.text === `${quantity === "position" ? "q" : quantity === "velocity" ? "v" : "a"}(t)`), "initial graph identifies its source observable"); }
  const calculus = documentFor(); calculus.constructions[0]!.inputs = { ...inputs, lengthUnit: "m", amplitude: 0.02, equilibrium: 0.03, timeUnit: "ms", tMax: 1000 * Math.PI / 2, timeScale: 0.01, ordinateScale: 200 }; calculus.quantities[0]!.value = 1000 * Math.PI / 8; calculus.quantities[0]!.unit = "ms"; calculus.constructions[1]!.inputs.time = "time"; calculus.quantities.push({ id: "scale", value: 250, unit: "ms" });
  for (const [id, kind, operator, values] of [["anchor", "point", "curve_anchor", { curve: "motion", at: { value: 100, unit: "ms" } }], ["derivative", "vector", "curve_derivative", { curve: "motion", at: "time", parameterScale: "scale" }], ["tangent", "line", "tangent_line", { curve: "motion", at: "time", span: 12 }], ["normal", "line", "normal_line", { curve: "motion", at: "time", span: 12 }], ["secant", "line", "curve_secant", { curve: "motion", first: { value: 200, unit: "ms" }, second: { value: 600, unit: "ms" }, span: 12 }]] as const) { calculus.entities.push({ id, kind, role: "exact harmonic calculus composition", ...(id === "derivative" ? { label: "dq" } : {}) }); calculus.constructions.push({ id: `make-${id}`, operator, inputs: values, outputs: [id] }); calculus.requiredEntityIds.push(id); calculus.revealGroups[0]!.entityIds.push(id); }
  calculus.assertions.push({ id: "exact-anchor", predicate: "incident", entities: ["anchor", "motion"], severity: "fatal" }, { id: "analytic-tangent", predicate: "parallel", entities: ["tangent", "derivative"], severity: "fatal", tolerance: 1e-8 }, { id: "analytic-normal", predicate: "perpendicular", entities: ["normal", "derivative"], severity: "fatal", tolerance: 1e-8 }); calculus.constructions.reverse(); compiled(calculus);
  const staleSlope = structuredClone(calculus); staleSlope.entities.find((entity) => entity.id === "derivative")!.label = "v=-0.08 m/s";
  const wrongParameterUnit = structuredClone(calculus); wrongParameterUnit.quantities.find((quantity) => quantity.id === "scale")!.unit = "s";
  const endpoint = structuredClone(calculus); endpoint.constructions.find((source) => source.operator === "tangent_line")!.inputs.at = 0;
  const alias = documentFor(); alias.constructions[0]!.inputs.samples = 2;
  const constant = documentFor(); constant.constructions[0]!.inputs.amplitude = 0; compiled(constant);
  const trueLabel = documentFor(); trueLabel.entities[1]!.label = "v=-8 cm/s"; check(compiled(trueLabel).some((primitive) => primitive.text === "v=-8 cm/s"), "explicit requested physical state labels use source authority");
  for (const invalid of [sourceUnitMismatch, timeUnitMismatch, wrongLabel, zeroAmplitudeUnderflow, cycle, wrongOutputs, wrongKind, staleSlope, wrongParameterUnit, endpoint, alias, megaMeter]) { const result = compileSceneDocument(invalid); check(!result.ok && result.renderScene === null, `invalid harmonic candidate cannot partially render: ${JSON.stringify(result.report.issues)}`); }
}
console.log(`harmonic motion operators verified: ${checks} independent phase, ODE, units, calculus, labels, and atomic rejection checks`);
