import { strict as assert } from "node:assert";
import { evaluateFluidConstruction, fluidGeometryLabel, validateEvaluatedFluidLabels, validateFluidConstruction, type FluidEvaluationContext } from "../../src/compile/fluidGeometry";
import { evaluateCalculusConstruction } from "../../src/compile/calculusGeometry";
import type { SceneConstruction, SceneDocument, SceneIssue } from "../../src/types";

const geometries = new Map<string, unknown>();
const quantities = new Map<string, number>([["rho", 1], ["gravity", 980], ["depth", 150], ["scale", 10]]);
const context: FluidEvaluationContext = { number(value) { if (typeof value === "object" && value !== null && "value" in value) return context.number(value.value); const result = typeof value === "string" && quantities.has(value) ? quantities.get(value)! : Number(value); if (!Number.isFinite(result)) throw new Error("non-numeric source"); return result; }, point() { throw new Error("physical geometry is not reinterpreted"); }, geometry: (value) => typeof value === "string" ? geometries.get(value) : undefined };
const inputs = { surfacePressure: 101.3, density: 1, gravity: 980, depthMin: 0, depthMax: 200, pressureUnit: "kPa", densityUnit: "g/cm^3", gravityUnit: "cm/s^2", depthUnit: "cm", depthScale: 0.1, pressureScale: 1, samples: 5 };
const output = evaluateFluidConstruction("hydrostatic_profile", inputs, context)[0]!;
assert.equal(output.kind, "path"); if (output.kind !== "path" || !("hydrostaticProfile" in output)) throw new Error("hydrostatic source must retain its physical profile");
assert.equal(output.hydrostaticProfile.pressureGradientSI, 9800);
assert.deepEqual(output.points.at(-1), { x: 20, y: 120.9 });
const force = evaluateFluidConstruction("buoyancy", { density: 1, gravity: 980, displacedVolume: 500, densityUnit: "g/cm^3", gravityUnit: "cm/s^2", volumeUnit: "cm^3", origin: [4, -3], displayLength: 12 }, context)[0]!;
assert.equal(force.kind, "path"); if (force.kind !== "path" || !("buoyancyDefinition" in force)) throw new Error("nonzero Archimedes force must retain SI authority");
assert.ok(Math.abs(force.buoyancyDefinition.forceSI - 4.9) < 1e-12);
assert.deepEqual(force.points, [{ x: 4, y: -3 }, { x: 4, y: 9 }]);
const construction = { id: "derive-force", operator: "buoyancy", inputs: { density: 1, gravity: 980, displacedVolume: 500, densityUnit: "g/cm^3", gravityUnit: "cm/s^2", volumeUnit: "cm^3", displayLength: 12 }, outputs: ["force"] };
const candidate: SceneDocument = { schemaVersion: "scene-document/v2", source: {}, quantities: [], entities: [{ id: "force", kind: "vector", role: "Archimedes force", label: "F_b=999 N" }], constructions: [construction], relations: [], assertions: [], annotations: [], requiredEntityIds: ["force"], revealGroups: [], teachingTimeline: [] };
const issues: SceneIssue[] = []; validateEvaluatedFluidLabels(construction, 0, candidate, [force], issues);
assert.ok(issues.some((issue) => issue.severity === "fatal"), "buoyancy labels cannot supply a contradictory source-independent force");
const wrongUnit = structuredClone(candidate); wrongUnit.entities[0]!.label = "F_b";
wrongUnit.quantities.push({ id: "rho", value: 1000, unit: "kg/m^3" }); wrongUnit.constructions[0]!.inputs.density = "rho";
const unitIssues: SceneIssue[] = []; validateFluidConstruction(wrongUnit.constructions[0]!, 0, wrongUnit, new Map([["force", wrongUnit.constructions[0]!]]), unitIssues);
assert.ok(unitIssues.some((issue) => issue.severity === "fatal"), "quantity-bound density cannot silently change its declared source scale");
let checks = 8;
function check(condition: unknown, message: string): void { checks++; assert.ok(condition, message); }
function close(actual: number, expected: number, message: string, tolerance = 1e-10): void { checks++; assert.ok(Math.abs(actual - expected) <= tolerance * Math.max(Math.abs(expected), 1e-300), `${message}: ${actual} != ${expected}`); }
function reject(operator: string, values: Record<string, unknown>): void { checks++; assert.throws(() => evaluateFluidConstruction(operator, values, context)); }
geometries.set("profile", output);
for (const depth of [0, 50, 75, 150, 200]) {
  const state = evaluateFluidConstruction("hydrostatic_state", { profile: "profile", depth: { value: depth, unit: "cm" } }, context)[0]!;
  if (state.kind !== "point" || !("hydrostaticState" in state)) throw new Error("state must retain SI authority");
  close(state.hydrostaticState.pressureSI, 101300 + 1000 * 9.8 * depth / 100, "independent hydrostatic pressure law");
  close(state.point.x, depth / 10, "source-depth display coordinate"); close(state.point.y, 101.3 + 0.098 * depth, "source-pressure display coordinate");
  assert.deepEqual(state.calculusAnchor, { curveId: "profile", parameter: depth }); assert.deepEqual(output.sampledCurve.evaluate(depth), state.point); checks += 2;
  assert.deepEqual(output.sampledCurve.derivative(depth), { x: 0.1, y: 0.098 }); checks++;
}
for (const [pressureUnit, surfacePressure, pressureScale] of [["Pa", 101300, 0.001], ["kPa", 101.3, 1], ["bar", 1.013, 100]] as const) for (const [depthUnit, depthMax, depthScale] of [["m", 2, 10], ["cm", 200, 0.1], ["mm", 2000, 0.01]] as const) {
  const curve = evaluateFluidConstruction("hydrostatic_profile", { ...inputs, pressureUnit, surfacePressure, pressureScale, depthUnit, depthMax, depthScale, density: 1000, densityUnit: "kg/m^3", gravity: 9.8, gravityUnit: "m/s^2", origin: [19, -31] }, context)[0]!;
  if (curve.kind !== "path" || !("hydrostaticProfile" in curve)) throw new Error("unit-invariant profile must retain source metadata");
  close(curve.hydrostaticProfile.pressureGradientSI, 9800, "SI gradient independent of source units");
  curve.points.forEach((point, i) => { close(point.x - 19, 5 * i, "unit-invariant translated depth"); close(point.y + 31, 101.3 + 4.9 * i, "unit-invariant translated pressure"); });
  const derivative = curve.sampledCurve.derivative(depthMax / 2); close(derivative.y / derivative.x, 0.98, "display slope differs from the SI gradient");
}
const gauge = evaluateFluidConstruction("hydrostatic_profile", { ...inputs, surfacePressure: 0 }, context)[0]!; if (gauge.kind !== "path") throw new Error("zero pressure source remains a profile"); assert.deepEqual(gauge.points[0], { x: 0, y: 0 }); checks++;
for (const [key, value] of [["surfacePressure", -1], ["surfacePressure", undefined], ["density", 0], ["gravity", 0], ["gravity", undefined], ["depthMin", -1], ["depthMax", 0], ["depthMax", Infinity], ["pressureUnit", "atm"], ["densityUnit", "kg"], ["gravityUnit", "1"], ["depthUnit", "s"], ["depthScale", 0], ["pressureScale", -1], ["samples", 1], ["samples", 514], ["samples", 4.5], ["origin", "projectedPoint"], ["openTank", true]] as const) reject("hydrostatic_profile", { ...inputs, [key]: value });
for (const overrides of [{ density: { value: 1000, unit: "kg/m^3" } }, { gravity: { value: 9.8, unit: "m/s^2" } }, { depthScale: { value: 0.1, unit: "cm" } }, { origin: [{ value: 0, unit: "m" }, 0] }, { origin: [1e12, 1e12], depthScale: 1e-6 }, { surfacePressure: 1, density: 1e-200, gravity: 1e-200 }, { surfacePressure: 1e12, density: 1e-200, gravity: 1 }, { density: 1e12, gravity: 1e12 }, { pressureScale: 1e-200 }, { depthScale: 1e-200 }, { surfacePressure: 1e-300, pressureUnit: "Pa", pressureScale: 1e-200 }]) reject("hydrostatic_profile", { ...inputs, ...overrides });
for (const depth of [-1, 201, NaN, undefined, { value: 1, unit: "m" }]) reject("hydrostatic_state", { profile: "profile", depth });
reject("hydrostatic_state", { profile: "profile", depth: 100, pressure: 1 });
geometries.set("foreign", { kind: "path", points: output.points }); reject("hydrostatic_state", { profile: "foreign", depth: 100 });
geometries.set("projected", { ...output, spacePlane: { normal: { x: 0, y: 0, z: 1 } } }); reject("hydrostatic_state", { profile: "projected", depth: 100 });
geometries.set("tampered", { ...output, hydrostaticProfile: { ...output.hydrostaticProfile, pressureGradientSI: 1 } }); reject("hydrostatic_state", { profile: "tampered", depth: 100 });
const forceInputs = construction.inputs;
reject("buoyancy", { ...forceInputs, volumeUnit: "ML" });
for (const [volumeUnit, displacedVolume] of [["cm^3", 500], ["m^3", 0.0005], ["L", 0.5], ["mL", 500]] as const) {
  const vector = evaluateFluidConstruction("buoyancy", { ...forceInputs, volumeUnit, displacedVolume }, context)[0]!;
  if (vector.kind !== "path" || !("buoyancyDefinition" in vector)) throw new Error("nonzero force must retain SI authority");
  close(vector.buoyancyDefinition.forceSI, 1000 * 9.8 * 0.0005, "independent Archimedes SI force"); assert.deepEqual(vector.buoyancyDefinition.direction, { x: 0, y: 1 }); checks++;
}
const scaled = evaluateFluidConstruction("buoyancy", { ...forceInputs, displayLength: undefined, displayScale: 2 }, context)[0]!; if (scaled.kind !== "path") throw new Error("scaled force must be a vector"); close(scaled.points[1]!.y - scaled.points[0]!.y, 9.8, "physical force and arrow scale compose");
const zero = evaluateFluidConstruction("buoyancy", { ...forceInputs, displacedVolume: 0 }, context)[0]!; if (zero.kind !== "point" || !("buoyancyDefinition" in zero)) throw new Error("certified zero volume produces a point");
check(zero.buoyancyDefinition.zero && zero.buoyancyDefinition.forceSI === 0 && zero.buoyancyDefinition.direction === null, "zero force is certified from explicit volume");
const tiny = evaluateFluidConstruction("buoyancy", { ...forceInputs, displacedVolume: 1e-200 }, context)[0]!; check(tiny.kind === "path" && "buoyancyDefinition" in tiny && tiny.buoyancyDefinition.forceSI > 0 && !tiny.buoyancyDefinition.zero, "tiny nonzero force cannot become a zero marker");
reject("buoyancy", { ...forceInputs, displacedVolume: "1e-400" });
for (const overrides of [{ displacedVolume: -1 }, { displacedVolume: undefined }, { density: 0 }, { gravity: undefined }, { volumeUnit: "m" }, { displayLength: 0 }, { displayLength: 1e-8 }, { displayScale: 1 }, { displayLength: undefined }, { displacedVolume: 1e-300, density: 1e-200 }, { displayLength: undefined, displayScale: 1e-300 }, { origin: [0, 1e12], displayLength: 1e-5 }, { origin: "physicalPoint" }, { displacedVolume: { value: 0.5, unit: "L" } }, { displayLength: { value: 12, unit: "N" } }, { density: 1e12, gravity: 1e12 }, { direction: [1, 0] }]) reject("buoyancy", { ...forceInputs, ...overrides });
assert.equal(fluidGeometryLabel(output), "p=p0+rho*g*d"); assert.equal(fluidGeometryLabel(scaled), "F_b"); assert.equal(fluidGeometryLabel(zero), "F_b"); checks += 3;
const at150 = evaluateFluidConstruction("hydrostatic_state", { profile: "profile", depth: 150 }, context)[0]!; assert.equal(fluidGeometryLabel(at150), "p(d)"); assert.equal(fluidGeometryLabel(at150, "p=116 kPa"), "p=116 kPa"); checks += 2;
const derivative = evaluateCalculusConstruction("curve_derivative", { curve: "profile", at: 150, parameterScale: 10 }, context)[0]!; if (derivative.kind !== "path") throw new Error("positive pressure gradient gives a nonzero display derivative");
close(derivative.points[1]!.x - derivative.points[0]!.x, 1, "derivative applies the source-depth parameter scale"); close(derivative.points[1]!.y - derivative.points[0]!.y, 0.98, "display derivative is separate from physical Pa/m gradient");
function documentFor(): SceneDocument {
  const constructions: SceneConstruction[] = [{ id: "make-profile", operator: "hydrostatic_profile", inputs: { ...inputs }, outputs: ["profile"] }, { id: "make-state", operator: "hydrostatic_state", inputs: { profile: "profile", depth: { value: "depth", unit: "cm" } }, outputs: ["state"] }, { id: "make-force", operator: "buoyancy", inputs: { ...forceInputs }, outputs: ["force"] }];
  return { schemaVersion: "scene-document/v2", source: { question: "Show the explicit pressure law and Archimedes force." }, visualDecision: { mode: "scene", reason: "verified fluid source quantities" }, quantities: [{ id: "depth", value: 150, unit: "cm" }], entities: [{ id: "profile", kind: "polyline", role: "hydrostatic pressure law" }, { id: "state", kind: "point", role: "exact pressure state" }, { id: "force", kind: "vector", role: "Archimedes force" }], constructions, relations: [], assertions: [], annotations: [], requiredEntityIds: ["profile", "state", "force"], revealGroups: [{ id: "setup", entityIds: ["profile", "state", "force"], dependsOn: [], narrationCue: "show explicit fluid law" }], teachingTimeline: [{ id: "show", action: "reveal", targetId: "setup", dependsOn: [], narrationIntent: "show verified fluid geometry" }] };
}
function issuesFor(scene: SceneDocument): SceneIssue[] { const found: SceneIssue[] = []; const map = new Map(scene.constructions.flatMap((source) => source.outputs.map((id) => [id, source] as const))); scene.constructions.forEach((source, index) => validateFluidConstruction(source, index, scene, map, found)); return found; }
function rejectDocument(scene: SceneDocument, code: string): void { check(issuesFor(scene).some((issue) => issue.code === code && issue.severity === "fatal"), `expected ${code}: ${JSON.stringify(issuesFor(scene))}`); }
assert.deepEqual(issuesFor(documentFor()), []); checks++;
const wrongProfileUnit = documentFor(); wrongProfileUnit.quantities.push({ id: "rho_si", value: 1000, unit: "kg/m^3" }); wrongProfileUnit.constructions[0]!.inputs.density = "rho_si"; rejectDocument(wrongProfileUnit, "invalid_hydrostatic_profile_units");
const wrongDepth = documentFor(); wrongDepth.quantities[0]!.unit = "m"; rejectDocument(wrongDepth, "invalid_hydrostatic_state_units");
const wrongLabel = documentFor(); wrongLabel.entities[2]!.label = "F_b=999 N"; rejectDocument(wrongLabel, "invalid_buoyancy_label");
for (const [index, label, valid] of [[0, "p=p0+rho*g*d", true], [0, "p0=101.3 kPa", true], [0, "dp/dd=9800 Pa/m", true], [0, "dp/dd=9800 kPa/m", false], [0, "p0=1 Pa", false], [1, "p=116 kPa", true], [1, "p=116000 Pa", true], [1, "p=116 Pa", false], [1, "d=1.5 m", true], [2, "F_b=4.9 N", true], [2, "F_b=0.0049 kN", true], [2, "F_b=-4.9 N", false], [2, "F_b=4.9 Pa", false], [2, "V=500 cm^3", true]] as const) { const scene = documentFor(); scene.entities[index]!.label = label; if (valid) { assert.deepEqual(issuesFor(scene), []); checks++; } else rejectDocument(scene, `invalid_${scene.constructions[index]!.operator}_label`); }
for (const [target, value, unit, text, valid] of [["state", 116000, "Pa", undefined, true], ["state", 1.5, "m", undefined, true], ["profile", 9800, "Pa/m", "dp/dd", true], ["profile", 101.3, "kPa", "p0", true], ["profile", 200, "cm", undefined, false], ["force", 4.9, "N", undefined, true], ["force", 0.0049, "kN", "F_b", true], ["force", 500, "cm^3", "V", true], ["force", 4.9, "Pa", undefined, false], ["force", 999, "N", "F_b", false]] as const) {
  const scene = documentFor(); scene.quantities.push({ id: "result", value, unit }); scene.annotations.push({ id: "result-label", kind: "label", targetIds: [target], text, quantityId: "result" }); if (valid) { assert.deepEqual(issuesFor(scene), []); checks++; } else rejectDocument(scene, `invalid_${scene.constructions.find((source) => source.outputs.includes(target))!.operator}_label`);
}
const quantityBound = documentFor(); quantityBound.quantities.push({ id: "rho", value: "1", unit: "g/cm^3" }, { id: "g", value: { value: "980", unit: "cm/s^2" }, unit: "cm/s^2" }); quantityBound.constructions[0]!.inputs.density = { value: "rho" }; quantityBound.constructions[0]!.inputs.gravity = "g"; assert.deepEqual(issuesFor(quantityBound), []); checks++;
const cycle = documentFor(); cycle.quantities.push({ id: "a", value: "b" }, { id: "b", value: "a" }); cycle.constructions[0]!.inputs.density = "a"; check(issuesFor(cycle).some((issue) => issue.severity === "fatal"), "cyclic source references fail closed");
const wrongKind = documentFor(); wrongKind.entities[2]!.kind = "point"; rejectDocument(wrongKind, "invalid_buoyancy_output_kind");
const wrongOutputs = documentFor(); wrongOutputs.constructions[0]!.outputs.push("state"); rejectDocument(wrongOutputs, "invalid_hydrostatic_profile_outputs");
const certifiedZero = documentFor(); certifiedZero.constructions[2]!.inputs.displacedVolume = 0; certifiedZero.entities[2]!.kind = "point"; assert.deepEqual(issuesFor(certifiedZero), []); checks++;
const underflowLabel = structuredClone(certifiedZero); underflowLabel.entities[2]!.label = "F_b=1e-400 N"; rejectDocument(underflowLabel, "invalid_buoyancy_label");
const megaLiters = documentFor(); megaLiters.constructions[2]!.inputs.volumeUnit = "ML"; check(issuesFor(megaLiters).some((issue) => issue.severity === "fatal"), "SI prefix case must not silently change megaliters into milliliters");
if (!process.argv.includes("--unit-only")) {
  const { compileSceneDocument } = await import("../../src/compile/compiler"); const { validateSceneDocument } = await import("../../src/document/validation"); const { isSupportedSceneOperator } = await import("../../src/index");
  function compiled(scene: SceneDocument) { const validated = validateSceneDocument(scene); assert.ok(validated.document, `fluid validation failed: ${JSON.stringify(validated.report.issues)}`); const result = compileSceneDocument(validated.document); assert.ok(result.ok && result.renderScene, `fluid compile failed: ${JSON.stringify(result.report.issues)}`); check(result.renderScene.primitives.every((primitive) => primitive.points.every((point) => Number.isFinite(point.x) && Number.isFinite(point.y))), "fluid ink remains finite"); return result.renderScene.primitives; }
  for (const operator of ["hydrostatic_profile", "hydrostatic_state", "buoyancy"]) check(isSupportedSceneOperator(operator), "fluid derivation has executable capability");
  const live = documentFor(); live.constructions.reverse(); live.assertions.push({ id: "exact-state", predicate: "incident", entities: ["state", "profile"], severity: "fatal", tolerance: 1e-8 }); const primitives = compiled(live);
  check(primitives.some((primitive) => primitive.entityId === "profile" && primitive.text === "p=p0+rho*g*d"), "default hydrostatic label describes the source law"); check(!primitives.some((primitive) => /^p=[+-]?\d/.test(primitive.text ?? "")), "unrequested solved pressure is absent");
  const arrow = primitives.find((primitive) => primitive.entityId === "force" && primitive.points.length === 2); check(arrow && arrow.points[1]!.y < arrow.points[0]!.y, "buoyancy points upward on the canvas"); check(compiled(certifiedZero).some((primitive) => primitive.entityId === "force" && primitive.kind === "point"), "certified zero force renders a point"); compiled(quantityBound);
  const calculus = documentFor(); calculus.quantities.push({ id: "anchor-depth", value: 75, unit: "cm" }, { id: "derivative-depth", value: 100, unit: "cm" }, { id: "parameter-scale", value: 10, unit: "cm" });
  for (const [id, kind, operator, values] of [["anchor", "point", "curve_anchor", { curve: "profile", at: "anchor-depth" }], ["derivative", "vector", "curve_derivative", { curve: "profile", at: "derivative-depth", parameterScale: "parameter-scale" }], ["tangent", "line", "tangent_line", { curve: "profile", at: "derivative-depth", span: 15 }], ["normal", "line", "normal_line", { curve: "profile", at: "derivative-depth", span: 15 }], ["secant", "line", "curve_secant", { curve: "profile", first: { value: 50, unit: "cm" }, second: { value: 125, unit: "cm" }, span: 15 }]] as const) { calculus.entities.push({ id, kind, role: "exact analytic fluid composition" }); calculus.constructions.push({ id: `make-${id}`, operator, inputs: values, outputs: [id] }); calculus.requiredEntityIds.push(id); calculus.revealGroups[0]!.entityIds.push(id); }
  calculus.assertions.push({ id: "exact-anchor", predicate: "incident", entities: ["anchor", "profile"], severity: "fatal" }, { id: "exact-tangent", predicate: "parallel", entities: ["tangent", "derivative"], severity: "fatal", tolerance: 1e-8 }, { id: "exact-normal", predicate: "perpendicular", entities: ["normal", "derivative"], severity: "fatal", tolerance: 1e-8 }, { id: "linear-law-secant", predicate: "parallel", entities: ["secant", "tangent"], severity: "fatal", tolerance: 1e-8 }); calculus.constructions.reverse(); compiled(calculus);
  const wrongParameterUnit = structuredClone(calculus); wrongParameterUnit.quantities.find((quantity) => quantity.id === "parameter-scale")!.unit = "m";
  const endpointTangent = structuredClone(calculus); endpointTangent.constructions.find((source) => source.operator === "tangent_line")!.inputs.at = 0;
  const falseProof = documentFor(); falseProof.assertions.push({ id: "false-fluid-proof", predicate: "perpendicular", entities: ["force", "profile"], severity: "fatal", tolerance: 1e-8 });
  const collapsed = documentFor(); collapsed.constructions[0]!.inputs.pressureScale = 1e-200; const missingGravity = documentFor(); delete missingGravity.constructions[0]!.inputs.gravity;
  const separatelyFalse = documentFor(); separatelyFalse.entities.push({ id: "false-label", kind: "label", role: "false solved claim", label: "p=999 Pa" }); separatelyFalse.constructions.push({ id: "make-false-label", operator: "label", inputs: { target: "state", text: "p=999 Pa" }, outputs: ["false-label"] });
  const requested = documentFor(); requested.entities[1]!.label = "p=116 kPa"; requested.entities[2]!.label = "F_b=4.9 N"; const requestedInk = compiled(requested); check(requestedInk.some((primitive) => primitive.text === "F_b=4.9 N") && requestedInk.some((primitive) => primitive.text === "p=116 kPa"), "explicit verified numeric labels use computed physical authority");
  const exactQuantity = documentFor(); exactQuantity.quantities.push({ id: "force-result", value: 0.0049, unit: "kN" }); exactQuantity.annotations.push({ id: "force-result-label", kind: "label", targetIds: ["force"], text: "F_b=0.0049 kN", quantityId: "force-result" }); compiled(exactQuantity);
  const falseQuantity = structuredClone(exactQuantity); falseQuantity.quantities.find((quantity) => quantity.id === "force-result")!.value = 99;
  const underflowQuantity = documentFor(); underflowQuantity.quantities.push({ id: "unresolved-volume", value: "1e-400", unit: "cm^3" }); underflowQuantity.constructions[2]!.inputs.displacedVolume = "unresolved-volume"; underflowQuantity.entities[2]!.kind = "point";
  for (const invalid of [wrongProfileUnit, wrongDepth, wrongLabel, wrongKind, wrongOutputs, cycle, wrongParameterUnit, endpointTangent, falseProof, collapsed, missingGravity, separatelyFalse, falseQuantity, underflowQuantity, underflowLabel, megaLiters]) { const result = compileSceneDocument(invalid); check(!result.ok && result.renderScene === null, `invalid fluid candidate cannot partially render: ${JSON.stringify(result.report.issues)}`); }
}
console.log(`fluid operators verified: ${checks} independent hydrostatic/Archimedes, unit, calculus, and atomic rejection checks`);
