import { strict as assert } from "node:assert";
import { evaluateRotationConstruction, rotationGeometryLabel, validateEvaluatedRotationLabels, validateRotationConstruction, type RotationEvaluationContext, type RotationVectorDefinition } from "../../src/compile/rotationGeometry";
import type { SceneConstruction, SceneDocument, SceneIssue } from "../../src/types";

const geometries = new Map<string, unknown>();
const context: RotationEvaluationContext = { number: Number, point() { throw new Error("no foreign physical coordinates"); }, geometry: (value) => typeof value === "string" ? geometries.get(value) : undefined };
const inputs = { radius: 2, angle: 0, angleUnit: "rad", angularVelocity: 3, angularAcceleration: 4, units: { length: "m", time: "s" }, angularVelocityUnit: "rad/s", angularAccelerationUnit: "rad/s^2", origin: [10, -20], displayScale: 5 };
const motion = evaluateRotationConstruction("rotational_motion", inputs, context)[0]!;
assert.equal(motion.kind, "point"); if (motion.kind !== "point" || !("rotationalMotion" in motion)) throw new Error("rotation anchor must retain explicit source metric");
assert.deepEqual(motion.point, { x: 20, y: -20 }); assert.deepEqual(motion.rotationalMotion.radialSI, { x: 2, y: 0 });
geometries.set("motion", motion);
const velocity = evaluateRotationConstruction("rotational_state", { motion: "motion", kind: "velocity", displayLength: 12 }, context)[0]!;
assert.equal(velocity.kind, "path"); if (velocity.kind !== "path") throw new Error("nonzero source angular velocity produces a tangent vector");
assert.deepEqual(velocity.rotationalVector.componentsSI, { x: 0, y: 6 }); assert.deepEqual(velocity.points, [{ x: 20, y: -20 }, { x: 20, y: -8 }]);
const torque = evaluateRotationConstruction("planar_torque", { leverArm: [4 / 3, 1], force: [4, 3], lengthUnit: "m", forceUnit: "N", displayLength: 12 }, context)[0]!;
assert.equal(torque.kind, "multi_path"); if (torque.kind !== "multi_path") throw new Error("nonzero signed torque requires a normal glyph");
assert.equal(torque.planarTorque.torqueSI, -(2 ** -52)); assert.equal(torque.planarTorque.pageNormal, "in");
const construction = { id: "make-v", operator: "rotational_state", inputs: { motion: "motion", kind: "velocity", displayLength: 12 }, outputs: ["v"] };
const scene: SceneDocument = { schemaVersion: "scene-document/v2", source: {}, quantities: [], entities: [{ id: "v", kind: "vector", role: "source-derived tangential velocity", label: "v=12 m/s" }], constructions: [construction], relations: [], assertions: [], annotations: [], requiredEntityIds: ["v"], revealGroups: [], teachingTimeline: [] };
const issues: SceneIssue[] = []; validateEvaluatedRotationLabels(construction, 0, scene, [velocity], issues);
assert.ok(issues.some((issue) => issue.severity === "fatal"), "normalized arrow length cannot become a physical velocity claim");
const wrongUnit = structuredClone(scene); wrongUnit.entities = [{ id: "motion", kind: "point", role: "explicit circular position" }]; wrongUnit.constructions = [{ id: "make-motion", operator: "rotational_motion", inputs: { ...inputs, radius: "radius_cm" }, outputs: ["motion"] }]; wrongUnit.quantities.push({ id: "radius_cm", value: 200, unit: "cm" });
const unitIssues: SceneIssue[] = []; validateRotationConstruction(wrongUnit.constructions[0]!, 0, wrongUnit, new Map([["motion", wrongUnit.constructions[0]!]]), unitIssues);
assert.ok(unitIssues.some((issue) => issue.code === "invalid_rotational_motion_units"), "known radius quantities must match their explicit source scale");
let checks = 9;
function check(condition: unknown, message: string): void { checks++; assert.ok(condition, message); }
function close(actual: number, expected: number, message: string, tolerance = 1e-10): void { checks++; assert.ok(Math.abs(actual - expected) <= tolerance * Math.max(Math.abs(expected), 1), `${message}: ${actual} != ${expected}`); }
function reject(operator: string, values: Record<string, unknown>): void { checks++; assert.throws(() => evaluateRotationConstruction(operator, values, context)); }
function definition(output: unknown): RotationVectorDefinition { if (typeof output !== "object" || output === null || !("rotationalVector" in output)) throw new Error("derived vector requires physical source metadata"); return output.rotationalVector as RotationVectorDefinition; }
const unresolved = evaluateRotationConstruction("rotational_motion", { ...inputs, radius: 1, angle: Math.PI / 4, angularVelocity: Number.MIN_VALUE, angularAcceleration: 0, origin: [0, 0], displayScale: 2 }, context)[0]!; geometries.set("unresolved", unresolved); reject("rotational_state", { motion: "unresolved", kind: "velocity", displayLength: 2 });
for (const [angle, omega] of [[0, Number.MIN_VALUE], [Math.PI / 4, 1e-300], [Math.PI / 3, -1e-300]]) {
  const anchor = evaluateRotationConstruction("rotational_motion", { ...inputs, radius: 1, angle, angularVelocity: omega, angularAcceleration: 0, origin: [0, 0], displayScale: 2 }, context)[0]!; geometries.set("conditioned", anchor);
  const arrow = evaluateRotationConstruction("rotational_state", { motion: "conditioned", kind: "velocity", displayLength: 2 }, context)[0]!; if (arrow.kind !== "path") throw new Error("certifiable nonzero small rates must retain vector geometry"); const delta = { x: arrow.points[1]!.x - arrow.points[0]!.x, y: arrow.points[1]!.y - arrow.points[0]!.y };
  close(Math.hypot(delta.x, delta.y), 2, "scaled normalization retains requested display length for certifiable tiny rates"); close(delta.x, -Math.sign(omega!) * Math.sin(angle!) * 2, "scaled normalization preserves independent tangent x direction"); close(delta.y, Math.sign(omega!) * Math.cos(angle!) * 2, "scaled normalization preserves independent tangent y direction");
}
for (const angle of [0, Math.PI / 2, Math.PI, Math.PI / 4, -Math.PI / 4, 1e-12, Math.PI / 2 + 1e-12]) for (const [omega, alpha] of [[3, 4], [-3, -4], [0, 4], [3, 0], [0, 0]]) {
  const anchor = evaluateRotationConstruction("rotational_motion", { ...inputs, angle, angularVelocity: omega, angularAcceleration: alpha }, context)[0]!; if (anchor.kind !== "point" || !("rotationalMotion" in anchor)) throw new Error("polar anchor must retain its metric"); geometries.set("rotated", anchor);
  const v = definition(evaluateRotationConstruction("rotational_state", { motion: "rotated", kind: "velocity", displayLength: 12 }, context)[0]); const a = definition(evaluateRotationConstruction("rotational_state", { motion: "rotated", kind: "acceleration", displayLength: 12 }, context)[0]); const components = evaluateRotationConstruction("rotational_state", { motion: "rotated", kind: "components", displayLength: 12 }, context); const at = definition(components[0]); const ac = definition(components[1]); const r = anchor.rotationalMotion.radialSI;
  close(r.x ** 2 + r.y ** 2, 4, "source angle changes direction without changing physical radius"); close(v.componentsSI.x * r.x + v.componentsSI.y * r.y, 0, "velocity is orthogonal to physical radius"); close(at.componentsSI.x * r.x + at.componentsSI.y * r.y, 0, "tangential acceleration is orthogonal to physical radius");
  close(ac.componentsSI.x * r.x + ac.componentsSI.y * r.y, -4 * omega! ** 2, "centripetal acceleration points inward for either rotation sign"); close(v.componentsSI.y * r.x - v.componentsSI.x * r.y, 4 * omega!, "velocity orientation follows signed omega"); close(at.componentsSI.y * r.x - at.componentsSI.x * r.y, 4 * alpha!, "tangential acceleration orientation follows signed alpha");
  close(ac.magnitudeSI, v.magnitudeSI ** 2 / 2, "independent v^2/r centripetal magnitude law"); close(a.magnitudeSI ** 2, 4 * (alpha! ** 2 + omega! ** 4), "orthogonal acceleration components combine by Pythagoras"); close(a.componentsSI.x, at.componentsSI.x + ac.componentsSI.x, "total acceleration x equals independently derived components"); close(a.componentsSI.y, at.componentsSI.y + ac.componentsSI.y, "total acceleration y equals independently derived components");
  check(v.zero === (omega === 0) && at.zero === (alpha === 0) && ac.zero === (omega === 0) && a.zero === (omega === 0 && alpha === 0), "each zero is certified independently from explicit source rates");
}
const converted = evaluateRotationConstruction("rotational_motion", { ...inputs, radius: 200, angularVelocity: 0.003, angularAcceleration: 0.000004, units: { length: "cm", time: "ms" }, angularVelocityUnit: "rad/ms", angularAccelerationUnit: "rad/ms^2", displayScale: 0.05 }, context)[0]!; if (converted.kind !== "point" || !("rotationalMotion" in converted)) throw new Error("converted rotation must remain source-defined"); geometries.set("converted", converted);
reject("rotational_motion", { ...inputs, units: { length: "Mm", time: "s" } });
reject("rotational_motion", { ...inputs, radius: { value: 2, unit: "Mm" }, units: { length: "mm", time: "s" } });
reject("rotational_motion", { ...inputs, units: { length: "m", time: "Ms" }, angularVelocityUnit: "rad/Ms", angularAccelerationUnit: "rad/Ms^2" });
assert.deepEqual(converted.point, motion.point); close(converted.rotationalMotion.radiusSI, 2, "centimetres to SI radius"); close(converted.rotationalMotion.angularVelocitySI, 3, "source radians per millisecond to SI omega"); close(converted.rotationalMotion.angularAccelerationSI, 4, "source radians per millisecond squared to SI alpha"); close(definition(evaluateRotationConstruction("rotational_state", { motion: "converted", kind: "velocity", displayLength: 22 }, context)[0]).magnitudeSI, 6, "SI speed independent of source units and normalized arrow length"); checks++;
for (const [key, value] of [["radius", 0], ["radius", -1], ["radius", "1e-400"], ["angle", Infinity], ["angle", 1e6 + 1], ["angleUnit", "deg"], ["angularVelocity", undefined], ["angularAcceleration", undefined], ["angularVelocityUnit", "Hz"], ["angularAccelerationUnit", "rad/s"], ["units", { length: "kg", time: "s" }], ["displayScale", 0], ["displayScale", 1e-200], ["origin", "worldPoint"], ["mass", 1]] as const) reject("rotational_motion", { ...inputs, [key]: value });
for (const overrides of [{ radius: { value: 200, unit: "cm" } }, { angularVelocity: { value: 3, unit: "rad/ms" } }, { angle: { value: 0, unit: "deg" } }, { displayScale: { value: 5, unit: "m" } }, { units: { length: "m", time: "ms" } }, { origin: [{ value: 0, unit: "m" }, 0] }, { origin: [1e12, 1e12], displayScale: 1e-5 }]) reject("rotational_motion", { ...inputs, ...overrides });
for (const overrides of [{ kind: "momentum" }, { displayLength: 0 }, { displayLength: 1e-8 }, { displayLength: { value: 12, unit: "m/s" } }, { origin: [0, 0] }, { motion: "missing" }]) reject("rotational_state", { motion: "motion", kind: "velocity", displayLength: 12, ...overrides });
geometries.set("tampered", { ...motion, rotationalMotion: { ...motion.rotationalMotion, angularVelocitySI: 999 } }); reject("rotational_state", { motion: "tampered", kind: "velocity", displayLength: 12 });
geometries.set("moved", { ...motion, point: { x: 0, y: 0 } }); reject("rotational_state", { motion: "moved", kind: "velocity", displayLength: 12 });
geometries.set("projected", { ...motion, space: {} }); reject("rotational_state", { motion: "projected", kind: "velocity", displayLength: 12 });
for (const [leverArm, force, expected] of [[[2, 3], [5, 7], -1], [[3, 2], [7, 5], 1], [[2, 3], [2, 3], 0], [[0, 0], [5, 7], 0], [[2, 3], [0, 0], 0], [[2, 0], [0, 7], 14]] as const) {
  const output = evaluateRotationConstruction("planar_torque", { leverArm, force, lengthUnit: "m", forceUnit: "N", origin: [19, -31], displayLength: 12 }, context)[0]!; if (!("planarTorque" in output)) throw new Error("page-normal torque must retain source cross product"); close(output.planarTorque.torqueSI, expected, "independent signed Cartesian torque oracle"); check(output.planarTorque.zero === (expected === 0) && output.planarTorque.pageNormal === (expected === 0 ? null : expected > 0 ? "out" : "in"), "normal glyph orientation follows independently verified torque sign");
}
const torqueCm = evaluateRotationConstruction("planar_torque", { leverArm: [200, 300], force: [5, 7], lengthUnit: "cm", forceUnit: "N", displayLength: 18 }, context)[0]!; if (!("planarTorque" in torqueCm)) throw new Error("converted torque must retain physical units"); close(torqueCm.planarTorque.torqueSI, -1, "unit conversion happens before any torque result is claimed");
for (const overrides of [{ leverArm: "normalizedArrow" }, { force: [5, 7, 9] }, { forceUnit: "kg" }, { lengthUnit: "s" }, { displayLength: 0 }, { displayLength: 1e-8 }, { leverArm: ["1e-400", 0] }, { leverArm: [1e-200, 0], force: [0, 1e-200] }, { leverArm: [1e12, 1e12], force: [1e12, -1e12] }, { origin: [1e12, 0], displayLength: 1e-5 }, { force: [{ value: 5, unit: "m" }, 7] }]) reject("planar_torque", { leverArm: [2, 3], force: [5, 7], lengthUnit: "m", forceUnit: "N", displayLength: 12, ...overrides });
assert.equal(rotationGeometryLabel(motion), "r"); assert.equal(rotationGeometryLabel(velocity), "v"); assert.equal(rotationGeometryLabel(torque), "tau"); assert.equal(rotationGeometryLabel(velocity, "v=6 m/s"), "v=6 m/s"); checks += 4;
function documentFor(): SceneDocument {
  const constructions: SceneConstruction[] = [{ id: "make-motion", operator: "rotational_motion", inputs: { ...inputs }, outputs: ["motion"] }, { id: "make-v", operator: "rotational_state", inputs: { motion: "motion", kind: "velocity", displayLength: 10 }, outputs: ["v"] }, { id: "make-components", operator: "rotational_state", inputs: { motion: "motion", kind: "components", displayLength: 12 }, outputs: ["at", "ac"] }, { id: "make-a", operator: "rotational_state", inputs: { motion: "motion", kind: "acceleration", displayLength: 14 }, outputs: ["a"] }, { id: "make-tau", operator: "planar_torque", inputs: { leverArm: [2, 3], force: [5, 7], lengthUnit: "m", forceUnit: "N", origin: [-10, 10], displayLength: 8 }, outputs: ["tau"] }];
  const entities = [{ id: "motion", kind: "point", role: "source-defined circular position" }, ...["v", "at", "ac", "a"].map((id) => ({ id, kind: "vector", role: "source-derived rotational vector" })), { id: "tau", kind: "polyline", role: "signed Cartesian page-normal torque" }]; const ids = entities.map((entity) => entity.id);
  return { schemaVersion: "scene-document/v2", source: { question: "Derive the explicit circular velocity, acceleration components, and planar torque." }, visualDecision: { mode: "scene", reason: "exact source rotational mechanics" }, quantities: [], entities, constructions, relations: [], assertions: [], annotations: [], requiredEntityIds: ids, revealGroups: [{ id: "setup", entityIds: ids, dependsOn: [], narrationCue: "show exact rotation geometry" }], teachingTimeline: [{ id: "show", action: "reveal", targetId: "setup", dependsOn: [], narrationIntent: "show source-derived rotation vectors" }] };
}
function issuesFor(candidate: SceneDocument): SceneIssue[] { const found: SceneIssue[] = []; const map = new Map(candidate.constructions.flatMap((source) => source.outputs.map((id) => [id, source] as const))); candidate.constructions.forEach((source, index) => validateRotationConstruction(source, index, candidate, map, found)); return found; }
function rejectDocument(candidate: SceneDocument, code: string): void { check(issuesFor(candidate).some((issue) => issue.code === code && issue.severity === "fatal"), `expected ${code}: ${JSON.stringify(issuesFor(candidate))}`); }
assert.deepEqual(issuesFor(documentFor()), []); checks++;
for (const [id, label, valid] of [["motion", "r=2 m", true], ["motion", "omega=3 rad/s", true], ["motion", "r=10 m", false], ["v", "v=6 m/s", true], ["v", "v=600 cm/s", true], ["v", "vy=6 m/s", true], ["v", "v=10 m/s", false], ["v", "v=-6 m/s", false], ["at", "a_t=8 m/s^2", true], ["ac", "a_c=18 m/s^2", true], ["ac", "a_c=12 m/s^2", false], ["tau", "tau=-1 N*m", true], ["tau", "tau=-100 N*cm", true], ["tau", "tau=1 N*m", false]] as const) { const candidate = documentFor(); candidate.entities.find((entity) => entity.id === id)!.label = label; if (valid) { assert.deepEqual(issuesFor(candidate), []); checks++; } else rejectDocument(candidate, `invalid_${candidate.constructions.find((source) => source.outputs.includes(id))!.operator}_label`); }
for (const [target, value, unit, text, valid] of [["motion", 2, "m", "r", true], ["motion", 3, "rad/s", "omega", true], ["v", 6, "m/s", "v", true], ["v", 6, "m/s", undefined, false], ["at", 8, "m/s^2", "a_t", true], ["ac", 18, "m/s^2", "a_c", true], ["tau", -100, "N*cm", undefined, true], ["tau", 1, "N*m", "tau", false]] as const) { const candidate = documentFor(); candidate.quantities.push({ id: "result", value, unit }); candidate.annotations.push({ id: "result-label", kind: "label", targetIds: [target], text, quantityId: "result" }); if (valid) { assert.deepEqual(issuesFor(candidate), []); checks++; } else rejectDocument(candidate, `invalid_${candidate.constructions.find((source) => source.outputs.includes(target))!.operator}_label`); }
const mismatched = documentFor(); mismatched.quantities.push({ id: "radius", value: 200, unit: "cm" }); mismatched.constructions[0]!.inputs.radius = "radius"; rejectDocument(mismatched, "invalid_rotational_motion_units");
const stale = documentFor(); stale.entities.find((entity) => entity.id === "v")!.label = "v=10 m/s"; rejectDocument(stale, "invalid_rotational_state_label");
const cyclic = documentFor(); cyclic.quantities.push({ id: "x", value: "y" }, { id: "y", value: "x" }); cyclic.constructions[0]!.inputs.radius = "x"; check(issuesFor(cyclic).some((issue) => issue.severity === "fatal"), "cyclic quantity references reject before geometry");
const wrongOutputs = documentFor(); wrongOutputs.constructions[2]!.outputs.pop(); rejectDocument(wrongOutputs, "invalid_rotational_state_outputs");
const wrongKind = documentFor(); wrongKind.entities.find((entity) => entity.id === "v")!.kind = "point"; rejectDocument(wrongKind, "invalid_rotational_state_output_kind");
const zeros = documentFor(); zeros.constructions[0]!.inputs.angularVelocity = 0; zeros.constructions[0]!.inputs.angularAcceleration = 0; ["v", "at", "ac", "a"].forEach((id) => { zeros.entities.find((entity) => entity.id === id)!.kind = "point"; }); zeros.constructions[4]!.inputs.force = [2, 3]; zeros.entities.find((entity) => entity.id === "tau")!.kind = "point"; assert.deepEqual(issuesFor(zeros), []); checks++;
const underflowClaim = structuredClone(zeros); underflowClaim.quantities.push({ id: "nonzero-component", value: Number.MIN_VALUE, unit: "cm/s" }); underflowClaim.annotations.push({ id: "false-zero-component", kind: "label", targetIds: ["v"], text: "vx", quantityId: "nonzero-component" }); rejectDocument(underflowClaim, "invalid_rotational_state_label");
const underflowText = structuredClone(zeros); underflowText.entities.find((entity) => entity.id === "tau")!.label = "tau=5e-324 N*cm"; rejectDocument(underflowText, "invalid_planar_torque_label");
if (!process.argv.includes("--unit-only")) {
  const { compileSceneDocument, validateSceneDocument, isSupportedSceneOperator } = await import("../../src/index");
  function compiled(candidate: SceneDocument) { const validated = validateSceneDocument(candidate); assert.ok(validated.document, `rotation validation failed: ${JSON.stringify(validated.report.issues)}`); const result = compileSceneDocument(validated.document); assert.ok(result.ok && result.renderScene, `rotation compile failed: ${JSON.stringify(result.report.issues)}`); check(result.renderScene.primitives.every((primitive) => primitive.points.every((point) => Number.isFinite(point.x) && Number.isFinite(point.y))), "rotation display ink remains finite"); return result.renderScene.primitives; }
  for (const operator of ["rotational_motion", "rotational_state", "planar_torque"]) check(isSupportedSceneOperator(operator), "rotation operator has executable capability");
  const live = documentFor(); live.constructions.reverse(); live.assertions.push({ id: "tangent-radial-orthogonality", predicate: "perpendicular", entities: ["at", "ac"], severity: "fatal", tolerance: 1e-8 }, { id: "v-at-parallel", predicate: "parallel", entities: ["v", "at"], severity: "fatal", tolerance: 1e-8 }); const ink = compiled(live); check(ink.some((primitive) => primitive.entityId === "tau" && primitive.kind === "polyline"), "signed normal torque glyph reaches live ink"); check(!ink.some((primitive) => /^(?:v|a|tau)=/.test(primitive.text ?? "")), "default rotation symbols do not expose unrequested solved answers"); compiled(zeros);
  const requested = documentFor(); requested.entities.find((entity) => entity.id === "v")!.label = "v=6 m/s"; requested.entities.find((entity) => entity.id === "tau")!.label = "tau=-1 N*m"; check(compiled(requested).some((primitive) => primitive.text === "v=6 m/s"), "explicit physical requests retain independently verified values");
  const annotation = documentFor(); annotation.quantities.push({ id: "wrong-result", value: 10, unit: "m/s" }); annotation.annotations.push({ id: "wrong-physical-label", kind: "label", targetIds: ["v"], text: "v", quantityId: "wrong-result" });
  const falseProof = documentFor(); falseProof.assertions.push({ id: "false-rotation", predicate: "parallel", entities: ["at", "ac"], severity: "fatal", tolerance: 1e-8 });
  const falseZero = documentFor(); falseZero.quantities.push({ id: "unresolved-rate", value: "1e-400", unit: "rad/s" }); falseZero.constructions[0]!.inputs.angularVelocity = "unresolved-rate";
  const wrongPrefix = documentFor(); wrongPrefix.constructions[0]!.inputs.units = { length: "Mm", time: "s" };
  const quantityPrefix = documentFor(); quantityPrefix.quantities.push({ id: "wrong-prefix-radius", value: 2, unit: "Mm" }); quantityPrefix.constructions[0]!.inputs.radius = "wrong-prefix-radius"; quantityPrefix.constructions[0]!.inputs.units = { length: "mm", time: "s" };
  const labelPrefix = documentFor(); labelPrefix.entities.find((entity) => entity.id === "motion")!.label = "r=2 Mm";
  const roundedDirection = documentFor(); roundedDirection.constructions = roundedDirection.constructions.slice(0, 2); roundedDirection.entities = roundedDirection.entities.filter((entity) => ["motion", "v"].includes(entity.id)); roundedDirection.requiredEntityIds = ["motion", "v"]; roundedDirection.revealGroups[0]!.entityIds = ["motion", "v"]; roundedDirection.constructions[0]!.inputs = { ...inputs, radius: 1, angle: Math.PI / 4, angularVelocity: Number.MIN_VALUE, angularAcceleration: 0, origin: [0, 0], displayScale: 2 }; roundedDirection.constructions[1]!.inputs.displayLength = 2;
  const incompatibleMetric = documentFor(); incompatibleMetric.constructions[1]!.inputs.displayLength = 12; incompatibleMetric.assertions.push({ id: "coincident-tangential-directions", predicate: "parallel", entities: ["v", "at"], severity: "fatal" }, { id: "false-physical-equality", predicate: "equal_length", entities: ["v", "at"], severity: "fatal" });
  const incompatible = compileSceneDocument(incompatibleMetric); check(!incompatible.ok && incompatible.renderScene === null, "normalized speed and acceleration arrows have incompatible physical metrics and cannot certify equal_length");
  for (const invalid of [mismatched, stale, cyclic, wrongOutputs, wrongKind, annotation, falseProof, falseZero, wrongPrefix, quantityPrefix, labelPrefix, roundedDirection, underflowClaim, underflowText]) { const result = compileSceneDocument(invalid); check(!result.ok && result.renderScene === null, `invalid rotational candidate cannot partially render: ${JSON.stringify(result.report.issues)}`); }
}
console.log(`rotation operators verified: ${checks} independent polar, tangent/centripetal, torque, unit, label, and atomic rejection checks`);
