export interface NarrationLabelRule {
  cues: string[];
  labels: string[];
}

/** Shared narration → board-label snap rules for physics, math, and chemistry (JEE-focused). */
export const JEE_NARRATION_LABEL_RULES: NarrationLabelRule[] = [
  // mechanics
  { cues: ["mass", "the mass", "mass is", "this mass", "labeled m", "label m"], labels: ["m", "M"] },
  { cues: ["friction", "frictional", "mu times", "mu is", "force of friction"], labels: ["f", "F_f", "f_k", "f_s"] },
  { cues: ["normal force", "normal from", "normal pushes", "normal", "surface pushes"], labels: ["N", "F_N"] },
  { cues: ["weight", "gravity", "gravitational", "mass times g", "mg", "w equals"], labels: ["mg", "W", "F_g"] },
  { cues: ["applied push", "applied force", "push to the right", "push to the left", "applied"], labels: ["F", "F_app", "P"] },
  { cues: ["tension", "rope pulls", "string pulls", "cable pulls"], labels: ["T", "F_T"] },
  { cues: ["spring force", "restoring force", "hookes law"], labels: ["F_s", "kx"] },
  { cues: ["centripetal", "centripetal force"], labels: ["F_c", "mv^2/r"] },
  { cues: ["velocity", "the velocity", "speed", "initial velocity", "final velocity"], labels: ["v", "V", "u"] },
  { cues: ["acceleration", "the acceleration", "accelerates"], labels: ["a", "A"] },
  { cues: ["force", "the force", "net force"], labels: ["F", "F_net"] },
  { cues: ["angle", "theta", "the angle", "inclination"], labels: ["θ", "theta"] },
  { cues: ["angular velocity", "spin rate", "omega", "rotates with"], labels: ["ω", "omega"] },
  { cues: ["angular acceleration", "alpha dot"], labels: ["α", "alpha"] },
  { cues: ["azimuth", "phi", "rotation angle"], labels: ["φ", "phi"] },
  { cues: ["coefficient", "mu", "friction coefficient"], labels: ["μ", "mu"] },
  { cues: ["distance", "displacement", "the distance"], labels: ["d", "x", "s"] },
  { cues: ["height", "the height", "falls from", "maximum height"], labels: ["h", "H"] },
  { cues: ["time", "the time", "time period"], labels: ["t", "T"] },
  { cues: ["radius", "the radius", "of the circle"], labels: ["r", "R"] },
  { cues: ["diameter"], labels: ["d", "D", "2r"] },
  { cues: ["moment of inertia", "rotational inertia"], labels: ["I", "MR^2"] },
  { cues: ["torque", "couple"], labels: ["τ", "tau"] },
  { cues: ["angular momentum"], labels: ["L", "Iω"] },
  // energy & momentum
  { cues: ["energy", "kinetic energy", "potential energy"], labels: ["E", "KE", "PE", "U"] },
  { cues: ["momentum", "the momentum", "linear momentum"], labels: ["p", "P", "mv"] },
  { cues: ["impulse"], labels: ["J", "FΔt"] },
  { cues: ["work done", "the work"], labels: ["W", "Fs"] },
  { cues: ["power", "the power"], labels: ["P"] },
  // gravitation & fluids
  { cues: ["gravitational force", "universal gravitation", "g m"], labels: ["F_g", "GMm/r^2"] },
  { cues: ["pressure", "the pressure", "hydrostatic"], labels: ["P", "p"] },
  { cues: ["density", "the density"], labels: ["ρ", "rho"] },
  { cues: ["volume", "the volume"], labels: ["V", "v"] },
  { cues: ["area", "the area", "cross section"], labels: ["A"] },
  { cues: ["surface tension"], labels: ["γ", "T", "S"] },
  { cues: ["viscosity"], labels: ["η", "eta"] },
  // waves & thermodynamics
  { cues: ["frequency", "the frequency", "angular frequency"], labels: ["f", "ν", "ω"] },
  { cues: ["wavelength", "the wavelength"], labels: ["λ", "lambda"] },
  { cues: ["amplitude", "the amplitude"], labels: ["A"] },
  { cues: ["phase", "phase constant"], labels: ["φ", "phi"] },
  { cues: ["temperature", "the temperature", "absolute temperature"], labels: ["T", "θ"] },
  { cues: ["heat", "heat supplied", "heat absorbed"], labels: ["Q", "ΔQ"] },
  { cues: ["entropy", "the entropy"], labels: ["S", "ΔS"] },
  { cues: ["enthalpy", "the enthalpy"], labels: ["H", "ΔH"] },
  { cues: ["gibbs energy", "gibbs free energy"], labels: ["G", "ΔG"] },
  // electricity & magnetism
  { cues: ["charge", "the charge", "point charge"], labels: ["q", "Q"] },
  { cues: ["current", "the current"], labels: ["I", "i"] },
  { cues: ["voltage", "potential difference", "the voltage", "emf"], labels: ["V", "ΔV", "ε"] },
  { cues: ["resistance", "the resistance"], labels: ["R"] },
  { cues: ["capacitance", "the capacitor"], labels: ["C"] },
  { cues: ["inductance", "the inductor"], labels: ["L"] },
  { cues: ["electric field", "field strength"], labels: ["E"] },
  { cues: ["magnetic field", "flux density"], labels: ["B"] },
  { cues: ["magnetic flux"], labels: ["Φ", "phi", "BA"] },
  { cues: ["permittivity"], labels: ["ε", "ε_0"] },
  { cues: ["permeability"], labels: ["μ", "μ_0"] },
  // optics & modern physics
  { cues: ["focal length", "focus"], labels: ["f"] },
  { cues: ["object distance", "object distance u"], labels: ["u"] },
  { cues: ["image distance", "image distance v"], labels: ["v"] },
  { cues: ["refractive index", "index of refraction"], labels: ["n", "μ"] },
  { cues: ["de broglie", "matter wave"], labels: ["λ", "h/p"] },
  { cues: ["photon energy", "planck"], labels: ["E", "hf", "hν"] },
  { cues: ["binding energy"], labels: ["E_b", "Δmc^2"] },
  // math — algebra & calculus
  { cues: ["discriminant", "delta of quadratic"], labels: ["Δ", "D", "b^2-4ac"] },
  { cues: ["slope", "gradient", "dy dx"], labels: ["m", "dy/dx"] },
  { cues: ["derivative", "differentiate"], labels: ["f'(x)", "dy/dx", "f'"] },
  { cues: ["integral", "integrate", "antiderivative", "integration"], labels: ["∫", "F(x)", "int"] },
  { cues: ["limit", "tends to"], labels: ["lim", "x→a"] },
  { cues: ["normal", "the normal", "normal line"], labels: ["N", "norm"] },
  { cues: ["inflection", "inflection point"], labels: ["IP"] },
  { cues: ["maxima", "maximum", "local max"], labels: ["max"] },
  { cues: ["minima", "minimum", "local min"], labels: ["min"] },
  { cues: ["summation", "sum of"], labels: ["Σ", "S_n"] },
  { cues: ["binomial coefficient", "n choose r"], labels: ["C(n,r)", "nCr"] },
  { cues: ["determinant", "det"], labels: ["|A|", "det(A)"] },
  { cues: ["eigenvalue", "characteristic"], labels: ["λ"] },
  { cues: ["complex number", "imaginary part", "real part"], labels: ["z", "a+ib", "Re(z)", "Im(z)"] },
  // math — coordinate geometry & vectors
  { cues: ["vertex", "the vertex", "parabola vertex"], labels: ["(h,k)", "V", "V1", "V2"] },
  { cues: ["focus", "the focus", "focal point"], labels: ["F", "S", "F1", "F2"] },
  { cues: ["directrix"], labels: ["x = -a", "L", "d", "D"] },
  { cues: ["eccentricity"], labels: ["e", "E"] },
  { cues: ["latus rectum"], labels: ["l", "LR"] },
  { cues: ["asymptote"], labels: ["asym"] },
  { cues: ["conjugate axis"], labels: ["2b"] },
  { cues: ["transverse axis"], labels: ["2a"] },
  { cues: ["semi major", "semi-major"], labels: ["a"] },
  { cues: ["semi minor", "semi-minor"], labels: ["b"] },
  { cues: ["origin", "coordinate origin"], labels: ["O", "(0,0)"] },
  { cues: ["vector", "the vector", "position vector"], labels: ["→a", "a⃗", "r⃗"] },
  { cues: ["dot product", "scalar product"], labels: ["a·b", "ab cos θ"] },
  { cues: ["cross product", "vector product"], labels: ["a×b", "ab sin θ"] },
  { cues: ["unit vector"], labels: ["î", "ĵ", "k̂", "n̂"] },
  // math — trigonometry & probability
  { cues: ["sine", "sin theta"], labels: ["sin θ", "sin"] },
  { cues: ["cosine", "cos theta"], labels: ["cos θ", "cos"] },
  { cues: ["tangent", "tan theta"], labels: ["tan θ", "tan", "T"] },
  { cues: ["probability", "chance"], labels: ["P", "P(A)"] },
  { cues: ["mean", "average", "expected value"], labels: ["μ", "E(X)", "x̄"] },
  { cues: ["variance", "standard deviation"], labels: ["σ^2", "σ", "Var(X)"] },
  // chemistry — physical
  { cues: ["mole", "moles", "amount of substance"], labels: ["n", "mol"] },
  { cues: ["molarity", "concentration molar"], labels: ["M", "mol/L"] },
  { cues: ["molality"], labels: ["m", "mol/kg"] },
  { cues: ["equilibrium constant", "k c", "k p"], labels: ["K_c", "K_p", "K"] },
  { cues: ["reaction quotient"], labels: ["Q"] },
  { cues: ["rate constant", "rate law"], labels: ["k", "k(T)"] },
  { cues: ["activation energy", "arrhenius"], labels: ["E_a", "Ea"] },
  { cues: ["nernst", "cell potential", "electrode potential"], labels: ["E", "E°", "E_cell"] },
  { cues: ["ph", "p h", "hydrogen ion"], labels: ["pH", "H+"] },
  { cues: ["pka", "acid dissociation"], labels: ["pKa", "K_a"] },
  { cues: ["pkb", "base dissociation"], labels: ["pKb", "K_b"] },
  { cues: ["solubility product"], labels: ["K_sp", "Ksp"] },
  { cues: ["van t hoff", "vant hoff"], labels: ["i"] },
  { cues: ["oxidation number", "oxidation state"], labels: ["ox", "n"] },
  { cues: ["hybridization", "hybridisation"], labels: ["sp", "sp2", "sp3", "dsp2"] },
  { cues: ["coordination number"], labels: ["CN"] },
  { cues: ["ligand"], labels: ["L", "NH3", "H2O"] },
  { cues: ["faraday", "faradays constant"], labels: ["F", "96500"] },
  // organic chemistry — reaction mechanisms
  { cues: ["nucleophile", "nucleophilic"], labels: ["Nu", "nuc"] },
  { cues: ["electrophile", "electrophilic"], labels: ["E", "elec"] },
  { cues: ["leaving group"], labels: ["LG", "leaving"] },
  { cues: ["carbocation"], labels: ["C+"] },
  { cues: ["carbanion"], labels: ["C-"] },
  { cues: ["radical", "free radical"], labels: ["R•", "rad"] },
  { cues: ["intermediate"], labels: ["I", "int"] },
  { cues: ["transition state"], labels: ["TS", "transition"] },
  { cues: ["markovnikov"], labels: ["Mark"] },
  { cues: ["resonance"], labels: ["res"] },
  { cues: ["sn1"], labels: ["SN1"] },
  { cues: ["sn2"], labels: ["SN2"] },
  { cues: ["e1"], labels: ["E1"] },
  { cues: ["e2"], labels: ["E2"] },
];
