import { circuit, concaveMirrorOracle, energyDiagram, pt, scene } from "./evaluationCompileProbes";

export const PHYSICS_EVALUATION_COMPILE_PROBES: Record<string, Record<string, unknown>> = {
  "mechanics-easy-incline-force": scene(
    "A 5 kg block rests on a rough horizontal floor. Draw the free-body diagram.",
    [
      { id: "origin", kind: "point", role: "body center" },
      { id: "body", kind: "rectangle", role: "block" },
      { id: "weight", kind: "vector", role: "weight" },
      { id: "normal", kind: "vector", role: "normal" },
      { id: "friction", kind: "vector", role: "friction" },
      { id: "applied", kind: "vector", role: "applied force" },
      { id: "applied_x", kind: "vector", role: "horizontal component" },
      { id: "applied_y", kind: "vector", role: "vertical component" },
      { id: "width", kind: "dimension", role: "body width" },
      { id: "weight_label", kind: "label", role: "weight label" },
    ],
    [
      { id: "make_origin", operator: "point", inputs: { x: 0, y: 0, coordinateSpace: "world" }, outputs: ["origin"] },
      { id: "make_body", operator: "rectangle", inputs: { center: "origin", width: 1.2, height: 0.8 }, outputs: ["body"] },
      { id: "make_weight", operator: "vector", inputs: { start: "origin", end: { x: 0, y: -2, coordinateSpace: "world" } }, outputs: ["weight"] },
      { id: "make_normal", operator: "vector", inputs: { start: "origin", end: { x: 0, y: 2, coordinateSpace: "world" } }, outputs: ["normal"] },
      { id: "make_friction", operator: "vector", inputs: { start: "origin", end: { x: -1.5, y: 0, coordinateSpace: "world" } }, outputs: ["friction"] },
      { id: "make_applied", operator: "vector", inputs: { start: "origin", end: { x: 1.6, y: 1.2, coordinateSpace: "world" } }, outputs: ["applied"] },
      { id: "make_components", operator: "vector_components", inputs: { origin: "origin", vector: [1.6, 1.2], basis: "friction" }, outputs: ["applied_x", "applied_y"] },
      { id: "make_width", operator: "dimension", inputs: { start: { x: -0.6, y: -0.4, coordinateSpace: "world" }, end: { x: 0.6, y: -0.4, coordinateSpace: "world" } }, outputs: ["width"] },
      { id: "make_weight_label", operator: "label", inputs: { target: "weight", text: "mg" }, outputs: ["weight_label"] },
    ],
    [
      { id: "normal_perp_friction", predicate: "perpendicular", entities: ["normal", "friction"], expected: true, severity: "fatal" },
      { id: "weight_opposite_normal", predicate: "opposite_direction", entities: ["weight", "normal"], expected: true, severity: "fatal" },
      { id: "weight_on_body", predicate: "connected", entities: ["weight", "body"], expected: true, severity: "fatal" },
    ],
  ),

  "mechanics-medium-projectile": scene(
    "A projectile is launched at 20 m/s at 30 degrees. Draw its trajectory.",
    [
      { id: "axes", kind: "axes", role: "axes" },
      { id: "path", kind: "polyline", role: "trajectory" },
      { id: "launch", kind: "point", role: "launch" },
      { id: "apex", kind: "point", role: "highest point" },
      { id: "land", kind: "point", role: "landing" },
      { id: "v0", kind: "vector", role: "launch velocity" },
      { id: "vx", kind: "vector", role: "horizontal component" },
      { id: "vy", kind: "vector", role: "vertical component" },
      { id: "v0_label", kind: "label", role: "velocity label" },
    ],
    [
      { id: "make_axes", operator: "axes", inputs: { xMin: -1, xMax: 40, yMin: -1, yMax: 8 }, outputs: ["axes"] },
      { id: "make_path", operator: "function_curve", inputs: { expression: "x/sqrt(3) - (x^2)/60", xMin: 0, xMax: 34.641, samples: 65 }, outputs: ["path"] },
      { id: "make_launch", operator: "point", inputs: { x: 0, y: 0, coordinateSpace: "world" }, outputs: ["launch"] },
      { id: "make_apex", operator: "point", inputs: { x: 17.320508, y: 5, coordinateSpace: "world" }, outputs: ["apex"] },
      { id: "make_land", operator: "point", inputs: { x: 34.641016, y: 0, coordinateSpace: "world" }, outputs: ["land"] },
      { id: "make_v0", operator: "vector", inputs: { start: "launch", end: { x: 3.4641016, y: 2, coordinateSpace: "world" } }, outputs: ["v0"] },
      { id: "make_components", operator: "vector_components", inputs: { origin: "launch", vector: [3.4641016, 2], basis: "path" }, outputs: ["vx", "vy"] },
      { id: "make_v0_label", operator: "label", inputs: { target: "v0", text: "u" }, outputs: ["v0_label"] },
    ],
    [
      { id: "apex_height", predicate: "function_value", entities: ["path"], expected: { x: 17.320508, y: 5 }, tolerance: 0.05, severity: "fatal" },
      { id: "apex_on_path", predicate: "on", entities: ["apex", "path"], expected: true, severity: "fatal" },
      { id: "lands", predicate: "root", entities: ["path"], expected: 0, severity: "fatal" },
      { id: "components_perp", predicate: "perpendicular", entities: ["vx", "vy"], expected: true, severity: "fatal" },
    ],
  ),

  "mechanics-hard-pulley-incline": scene(
    "A block on a 37 degree incline is connected over a pulley to a hanging block.",
    [
      { id: "pulley_c", kind: "point", role: "pulley center" },
      { id: "hang", kind: "point", role: "hanging block" },
      { id: "incline", kind: "point", role: "incline block" },
      { id: "ramp", kind: "line", role: "incline" },
      { id: "wheel", kind: "circle", role: "pulley" },
      { id: "block_hang", kind: "rectangle", role: "hanging block" },
      { id: "block_incline", kind: "rectangle", role: "incline block" },
      { id: "string", kind: "polyline", role: "string" },
      { id: "tension", kind: "vector", role: "tension" },
      { id: "weight", kind: "vector", role: "hanging weight" },
      { id: "tx", kind: "vector", role: "tension along incline" },
      { id: "ty", kind: "vector", role: "normal component" },
      { id: "tension_label", kind: "label", role: "tension label" },
    ],
    [
      { id: "make_pulley_c", operator: "point", inputs: { x: 2, y: 2, coordinateSpace: "world" }, outputs: ["pulley_c"] },
      { id: "make_hang", operator: "point", inputs: { x: 2, y: 0, coordinateSpace: "world" }, outputs: ["hang"] },
      { id: "make_incline", operator: "point", inputs: { x: 0, y: 0, coordinateSpace: "world" }, outputs: ["incline"] },
      { id: "make_ramp", operator: "line", inputs: { start: { x: -1, y: -0.75, coordinateSpace: "world" }, end: { x: 1.5, y: 1.125, coordinateSpace: "world" } }, outputs: ["ramp"] },
      { id: "make_wheel", operator: "circle", inputs: { center: "pulley_c", radius: 0.25 }, outputs: ["wheel"] },
      { id: "make_block_hang", operator: "rectangle", inputs: { center: "hang", width: 0.5, height: 0.5 }, outputs: ["block_hang"] },
      { id: "make_block_incline", operator: "rectangle", inputs: { center: "incline", width: 0.6, height: 0.4 }, outputs: ["block_incline"] },
      { id: "make_string", operator: "polyline", inputs: { points: ["incline", "pulley_c", "hang"] }, outputs: ["string"] },
      { id: "make_tension", operator: "vector", inputs: { start: "hang", end: "pulley_c" }, outputs: ["tension"] },
      { id: "make_weight", operator: "vector", inputs: { start: "hang", end: { x: 2, y: -1, coordinateSpace: "world" } }, outputs: ["weight"] },
      { id: "make_components", operator: "vector_components", inputs: { origin: "incline", vector: [0, -1], basis: "ramp" }, outputs: ["tx", "ty"] },
      { id: "make_tension_label", operator: "label", inputs: { target: "tension", text: "T" }, outputs: ["tension_label"] },
    ],
    [
      { id: "string_connected", predicate: "connected", entities: ["string", "block_hang"], expected: true, severity: "fatal" },
      { id: "weight_down", predicate: "opposite_direction", entities: ["weight", "tension"], expected: true, severity: "fatal" },
      { id: "components_perp", predicate: "perpendicular", entities: ["tx", "ty"], expected: true, severity: "fatal" },
      { id: "tx_along_ramp", predicate: "parallel", entities: ["tx", "ramp"], expected: true, severity: "fatal" },
    ],
  ),

  "fluids-easy-hydraulic-lift": (() => {
    const smallL = pt("small_l", -0.2, 1, "small piston left");
    const smallR = pt("small_r", 0.2, 1, "small piston right");
    const largeL = pt("large_l", 2, 1, "large piston left");
    const largeR = pt("large_r", 4, 1, "large piston right");
    const small = pt("small", 0, 1, "small piston");
    const large = pt("large", 3, 1, "large piston");
    return scene(
      "A hydraulic lift has pistons of radii 2 cm and 10 cm.",
      [
        small.entity, large.entity, smallL.entity, smallR.entity, largeL.entity, largeR.entity,
        { id: "small_piston", kind: "rectangle", role: "small piston" },
        { id: "large_piston", kind: "rectangle", role: "large piston" },
        { id: "fluid", kind: "connector", role: "fluid connection" },
        { id: "small_dim", kind: "dimension", role: "small diameter" },
        { id: "large_dim", kind: "dimension", role: "large diameter" },
        { id: "fin", kind: "vector", role: "input force" },
        { id: "fout", kind: "vector", role: "output force" },
        { id: "fin_label", kind: "label", role: "input label" },
      ],
      [
        small.construction, large.construction, smallL.construction, smallR.construction, largeL.construction, largeR.construction,
        { id: "make_small_piston", operator: "rectangle", inputs: { center: "small", width: 0.4, height: 0.3 }, outputs: ["small_piston"] },
        { id: "make_large_piston", operator: "rectangle", inputs: { center: "large", width: 2, height: 0.3 }, outputs: ["large_piston"] },
        { id: "make_fluid", operator: "connect", inputs: { start: "small", end: "large" }, outputs: ["fluid"] },
        { id: "make_small_dim", operator: "dimension", inputs: { start: "small_l", end: "small_r" }, outputs: ["small_dim"] },
        { id: "make_large_dim", operator: "dimension", inputs: { start: "large_l", end: "large_r" }, outputs: ["large_dim"] },
        { id: "make_fin", operator: "vector", inputs: { start: { x: 0, y: 1.4, coordinateSpace: "world" }, end: "small" }, outputs: ["fin"] },
        { id: "make_fout", operator: "vector", inputs: { start: "large", end: { x: 3, y: 2, coordinateSpace: "world" } }, outputs: ["fout"] },
        { id: "make_fin_label", operator: "label", inputs: { target: "fin", text: "F" }, outputs: ["fin_label"] },
      ],
      [
        { id: "pistons_connected", predicate: "connected", entities: ["small_piston", "fluid"], expected: true, severity: "fatal" },
        { id: "dims_parallel", predicate: "parallel", entities: ["small_dim", "large_dim"], expected: true, severity: "fatal" },
        { id: "radius_ratio", predicate: "distance_ratio", entities: ["large_l", "large_r", "small_l", "small_r"], expected: 5, severity: "fatal" },
      ],
    );
  })(),

  "fluids-medium-venturi": scene(
    "Water flows through a pipe that narrows from 4 cm to 2 cm.",
    [
      { id: "pipe", kind: "polygon", role: "venturi pipe" },
      { id: "axis", kind: "polyline", role: "flow axis" },
      { id: "wide_dim", kind: "dimension", role: "wide diameter" },
      { id: "narrow_dim", kind: "dimension", role: "narrow diameter" },
      { id: "flow", kind: "vector", role: "flow" },
      { id: "flow_label", kind: "label", role: "flow label" },
      { id: "wide_top", kind: "point", role: "wide top" },
      { id: "wide_bot", kind: "point", role: "wide bottom" },
      { id: "narrow_top", kind: "point", role: "narrow top" },
      { id: "narrow_bot", kind: "point", role: "narrow bottom" },
    ],
    [
      { id: "make_wide_top", operator: "point", inputs: { x: 0, y: 2, coordinateSpace: "world" }, outputs: ["wide_top"] },
      { id: "make_wide_bot", operator: "point", inputs: { x: 0, y: 0, coordinateSpace: "world" }, outputs: ["wide_bot"] },
      { id: "make_narrow_top", operator: "point", inputs: { x: 4, y: 1.5, coordinateSpace: "world" }, outputs: ["narrow_top"] },
      { id: "make_narrow_bot", operator: "point", inputs: { x: 4, y: 0.5, coordinateSpace: "world" }, outputs: ["narrow_bot"] },
      {
        id: "make_pipe",
        operator: "polygon",
        inputs: { points: [
          { x: 0, y: 0, coordinateSpace: "world" },
          { x: 2, y: 0, coordinateSpace: "world" },
          { x: 3, y: 0.5, coordinateSpace: "world" },
          { x: 5, y: 0.5, coordinateSpace: "world" },
          { x: 5, y: 1.5, coordinateSpace: "world" },
          { x: 3, y: 1.5, coordinateSpace: "world" },
          { x: 2, y: 2, coordinateSpace: "world" },
          { x: 0, y: 2, coordinateSpace: "world" },
        ] },
        outputs: ["pipe"],
      },
      {
        id: "make_axis",
        operator: "polyline",
        inputs: { points: [
          { x: 0, y: 1, coordinateSpace: "world" },
          { x: 5, y: 1, coordinateSpace: "world" },
        ] },
        outputs: ["axis"],
      },
      { id: "make_wide_dim", operator: "dimension", inputs: { start: "wide_bot", end: "wide_top" }, outputs: ["wide_dim"] },
      { id: "make_narrow_dim", operator: "dimension", inputs: { start: "narrow_bot", end: "narrow_top" }, outputs: ["narrow_dim"] },
      { id: "make_flow", operator: "vector", inputs: { start: { x: 0.5, y: 1, coordinateSpace: "world" }, end: { x: 2, y: 1, coordinateSpace: "world" } }, outputs: ["flow"] },
      { id: "make_flow_label", operator: "label", inputs: { target: "flow", text: "v" }, outputs: ["flow_label"] },
    ],
    [
      { id: "dims_parallel", predicate: "parallel", entities: ["wide_dim", "narrow_dim"], expected: true, severity: "fatal" },
      { id: "diameter_ratio", predicate: "distance_ratio", entities: ["wide_bot", "wide_top", "narrow_bot", "narrow_top"], expected: 2, severity: "fatal" },
      { id: "flow_on_axis", predicate: "connected", entities: ["flow", "axis"], expected: true, severity: "fatal" },
    ],
  ),

  "thermal-hard-pv-cycle": scene(
    "A gas executes the clockwise rectangular cycle A(V0,P0) to D to C to B to A.",
    [
      { id: "A", kind: "point", role: "corner", label: "A" },
      { id: "D", kind: "point", role: "corner", label: "D" },
      { id: "C", kind: "point", role: "corner", label: "C" },
      { id: "B", kind: "point", role: "corner", label: "B" },
      { id: "cycle", kind: "polyline", role: "P-V cycle" },
      { id: "sense", kind: "vector", role: "cycle direction" },
      { id: "Paxis", kind: "line", role: "P axis" },
      { id: "Vaxis", kind: "line", role: "V axis" },
      { id: "A_label", kind: "label", role: "corner A" },
      { id: "above_D", kind: "point", role: "isochore extension" },
      { id: "axes", kind: "axes", role: "P-V axes" },
    ],
    [
      { id: "make_A", operator: "point", inputs: { x: 0.002, y: 1e5, coordinateSpace: "world" }, outputs: ["A"] },
      { id: "make_D", operator: "point", inputs: { x: 0.002, y: 2e5, coordinateSpace: "world" }, outputs: ["D"] },
      { id: "make_C", operator: "point", inputs: { x: 0.004, y: 2e5, coordinateSpace: "world" }, outputs: ["C"] },
      { id: "make_B", operator: "point", inputs: { x: 0.004, y: 1e5, coordinateSpace: "world" }, outputs: ["B"] },
      { id: "make_cycle", operator: "polyline", inputs: { points: ["A", "D", "C", "B", "A"] }, outputs: ["cycle"] },
      { id: "make_sense", operator: "vector", inputs: { start: "A", end: "D" }, outputs: ["sense"] },
      { id: "make_Paxis", operator: "line", inputs: { start: "A", direction: [0, 1] }, outputs: ["Paxis"] },
      { id: "make_Vaxis", operator: "line", inputs: { start: "A", direction: [1, 0] }, outputs: ["Vaxis"] },
      { id: "make_A_label", operator: "label", inputs: { target: "A", text: "A" }, outputs: ["A_label"] },
      { id: "make_above_D", operator: "point", inputs: { x: 0.002, y: 3e5, coordinateSpace: "world" }, outputs: ["above_D"] },
      { id: "make_axes", operator: "axes", inputs: { xMin: 0, xMax: 0.005, yMin: 0, yMax: 3e5 }, outputs: ["axes"] },
    ],
    [
      { id: "closed", predicate: "connected", entities: ["A", "D", "C", "B"], expected: true, severity: "fatal" },
      { id: "a_on_vaxis", predicate: "on", entities: ["A", "Vaxis"], expected: true, severity: "fatal" },
      { id: "d_between", predicate: "between", entities: ["D", "A", "above_D"], expected: true, severity: "fatal" },
    ],
  ),

  "shm-easy-spring": scene(
    "A block attached to a horizontal spring oscillates with amplitude 0.10 m.",
    [
      { id: "eq", kind: "point", role: "equilibrium" },
      { id: "left", kind: "point", role: "left extreme" },
      { id: "right", kind: "point", role: "right extreme" },
      { id: "spring", kind: "polyline", role: "spring" },
      { id: "block", kind: "rectangle", role: "block" },
      { id: "amp", kind: "dimension", role: "amplitude" },
      { id: "eq_label", kind: "label", role: "equilibrium label" },
    ],
    [
      { id: "make_eq", operator: "point", inputs: { x: 0, y: 0, coordinateSpace: "world" }, outputs: ["eq"] },
      { id: "make_left", operator: "point", inputs: { x: -0.1, y: 0, coordinateSpace: "world" }, outputs: ["left"] },
      { id: "make_right", operator: "point", inputs: { x: 0.1, y: 0, coordinateSpace: "world" }, outputs: ["right"] },
      { id: "make_spring", operator: "polyline", inputs: { points: [{ x: -0.4, y: 0, coordinateSpace: "world" }, "left"] }, outputs: ["spring"] },
      { id: "make_block", operator: "rectangle", inputs: { center: "eq", width: 0.05, height: 0.04 }, outputs: ["block"] },
      { id: "make_amp", operator: "dimension", inputs: { start: "eq", end: "right" }, outputs: ["amp"] },
      { id: "make_eq_label", operator: "label", inputs: { target: "eq", text: "O" }, outputs: ["eq_label"] },
    ],
    [
      { id: "collinear", predicate: "collinear", entities: ["left", "eq", "right"], expected: true, severity: "fatal" },
      { id: "equal_amp", predicate: "equal_length", entities: ["left", "eq", "eq", "right"], expected: true, severity: "fatal" },
      { id: "eq_between", predicate: "between", entities: ["eq", "left", "right"], expected: true, severity: "fatal" },
    ],
  ),

  "shm-medium-pendulum": scene(
    "A simple pendulum of length 1.0 m is displaced through a small angle.",
    [
      { id: "pivot", kind: "point", role: "pivot" },
      { id: "mean", kind: "point", role: "mean position" },
      { id: "bob", kind: "point", role: "displaced bob" },
      { id: "mean_string", kind: "segment", role: "mean string" },
      { id: "displaced_string", kind: "segment", role: "displaced string" },
      { id: "swing", kind: "arc", role: "angular displacement" },
      { id: "bob_circle", kind: "circle", role: "bob" },
      { id: "restore", kind: "vector", role: "restoring" },
      { id: "length_dim", kind: "dimension", role: "length" },
      { id: "pivot_label", kind: "label", role: "pivot label" },
    ],
    [
      { id: "make_pivot", operator: "point", inputs: { x: 0, y: 0, coordinateSpace: "world" }, outputs: ["pivot"] },
      { id: "make_mean", operator: "point", inputs: { x: 0, y: -1, coordinateSpace: "world" }, outputs: ["mean"] },
      { id: "make_bob", operator: "rotate", inputs: { point: "mean", center: "pivot", angle: 0.3 }, outputs: ["bob"] },
      { id: "make_mean_string", operator: "segment", inputs: { start: "pivot", end: "mean" }, outputs: ["mean_string"] },
      { id: "make_displaced_string", operator: "segment", inputs: { start: "pivot", end: "bob" }, outputs: ["displaced_string"] },
      { id: "make_swing", operator: "arc", inputs: { center: "pivot", radius: 0.3, startAngle: -90, endAngle: -73, angleUnit: "degrees" }, outputs: ["swing"] },
      { id: "make_bob_circle", operator: "circle", inputs: { center: "bob", radius: 0.08 }, outputs: ["bob_circle"] },
      { id: "make_restore", operator: "vector", inputs: { start: "bob", end: "mean" }, outputs: ["restore"] },
      { id: "make_length_dim", operator: "dimension", inputs: { start: "pivot", end: "mean" }, outputs: ["length_dim"] },
      { id: "make_pivot_label", operator: "label", inputs: { target: "pivot", text: "O" }, outputs: ["pivot_label"] },
    ],
    [
      { id: "equal_length", predicate: "equal_length", entities: ["mean_string", "displaced_string"], expected: true, severity: "fatal" },
      { id: "string_connected", predicate: "connected", entities: ["displaced_string", "bob"], expected: true, severity: "fatal" },
      { id: "bob_on_string", predicate: "on", entities: ["bob", "displaced_string"], expected: true, severity: "fatal" },
    ],
  ),

  "waves-hard-third-harmonic": scene(
    "A string fixed at both ends vibrates in its third harmonic.",
    [
      { id: "axes", kind: "axes", role: "axes" },
      { id: "wave", kind: "polyline", role: "standing wave" },
      { id: "n0", kind: "point", role: "node" },
      { id: "n1", kind: "point", role: "node" },
      { id: "n2", kind: "point", role: "node" },
      { id: "n3", kind: "point", role: "node" },
      { id: "length_dim", kind: "dimension", role: "length" },
      { id: "wave_label", kind: "label", role: "harmonic label" },
    ],
    [
      { id: "make_axes", operator: "axes", inputs: { xMin: -0.1, xMax: 1.4, yMin: -1.2, yMax: 1.2 }, outputs: ["axes"] },
      { id: "make_wave", operator: "function_curve", inputs: { expression: "sin(3*3.141592653589793*x/1.2)", xMin: 0, xMax: 1.2, samples: 97 }, outputs: ["wave"] },
      { id: "make_n0", operator: "point", inputs: { x: 0, y: 0, coordinateSpace: "world" }, outputs: ["n0"] },
      { id: "make_n1", operator: "point", inputs: { x: 0.4, y: 0, coordinateSpace: "world" }, outputs: ["n1"] },
      { id: "make_n2", operator: "point", inputs: { x: 0.8, y: 0, coordinateSpace: "world" }, outputs: ["n2"] },
      { id: "make_n3", operator: "point", inputs: { x: 1.2, y: 0, coordinateSpace: "world" }, outputs: ["n3"] },
      { id: "make_length_dim", operator: "dimension", inputs: { start: "n0", end: "n3" }, outputs: ["length_dim"] },
      { id: "make_wave_label", operator: "label", inputs: { target: "wave", text: "n=3" }, outputs: ["wave_label"] },
    ],
    [
      { id: "node0", predicate: "root", entities: ["wave"], expected: 0, severity: "fatal" },
      { id: "antinode", predicate: "function_value", entities: ["wave"], expected: { x: 0.2, y: 1 }, tolerance: 0.02, severity: "fatal" },
      { id: "node_count", predicate: "entity_count", entities: ["n0", "n1", "n2", "n3"], expected: 4, severity: "fatal" },
      { id: "n1_on_wave", predicate: "on", entities: ["n1", "wave"], expected: true, severity: "fatal" },
    ],
  ),

  "electrostatics-easy-null-point": scene(
    "Two positive charges +4 uC and +1 uC are 3.0 m apart. Locate the null point.",
    [
      { id: "q4", kind: "point", role: "+4 uC" },
      { id: "q1", kind: "point", role: "+1 uC" },
      { id: "null", kind: "point", role: "null point" },
      { id: "join", kind: "segment", role: "joining line" },
      { id: "e4", kind: "vector", role: "field of 4 uC" },
      { id: "e1", kind: "vector", role: "field of 1 uC" },
      { id: "d4", kind: "dimension", role: "distance from 4 uC" },
      { id: "null_label", kind: "label", role: "null label" },
    ],
    [
      { id: "make_q4", operator: "point", inputs: { x: 0, y: 0, coordinateSpace: "world" }, outputs: ["q4"] },
      { id: "make_q1", operator: "point", inputs: { x: 3, y: 0, coordinateSpace: "world" }, outputs: ["q1"] },
      { id: "make_null", operator: "point", inputs: { x: 2, y: 0, coordinateSpace: "world" }, outputs: ["null"] },
      { id: "make_join", operator: "segment", inputs: { start: "q4", end: "q1" }, outputs: ["join"] },
      { id: "make_e4", operator: "vector", inputs: { start: "null", end: { x: 2.5, y: 0, coordinateSpace: "world" } }, outputs: ["e4"] },
      { id: "make_e1", operator: "vector", inputs: { start: "null", end: { x: 1.5, y: 0, coordinateSpace: "world" } }, outputs: ["e1"] },
      { id: "make_d4", operator: "dimension", inputs: { start: "q4", end: "null" }, outputs: ["d4"] },
      { id: "make_null_label", operator: "label", inputs: { target: "null", text: "P" }, outputs: ["null_label"] },
    ],
    [
      { id: "null_between", predicate: "between", entities: ["null", "q4", "q1"], expected: true, severity: "fatal" },
      { id: "collinear", predicate: "collinear", entities: ["q4", "null", "q1"], expected: true, severity: "fatal" },
      { id: "distance_ratio", predicate: "distance_ratio", entities: ["q4", "null", "null", "q1"], expected: 2, severity: "fatal" },
      { id: "fields_opposite", predicate: "opposite_direction", entities: ["e4", "e1"], expected: true, severity: "fatal" },
    ],
  ),

  "current-medium-series-parallel-source": circuit(
    "A 12 V battery and a 2 ohm resistor are in series with a parallel combination of 6 ohm and 3 ohm.",
    [
      { id: "n0", x: 0, y: 0 },
      { id: "n1", x: 1, y: 0 },
      { id: "n2", x: 2, y: 0 },
      { id: "n3", x: 3, y: 0 },
      { id: "n4", x: 4, y: 0 },
    ],
    [
      { id: "src", symbol: "battery", start: "n0", end: "n1", role: "source" },
      { id: "r2", symbol: "resistor", start: "n1", end: "n2", role: "2 ohm" },
      { id: "r6", symbol: "resistor", start: "n2", end: "n3", role: "6 ohm" },
      { id: "r3", symbol: "resistor", start: "n2", end: "n3", role: "3 ohm" },
    ],
    {
      connectors: [{ id: "lead", start: "n3", end: "n4" }],
      extraEntities: [
        { id: "i_total", kind: "vector", role: "total current" },
        { id: "i_label", kind: "label", role: "current label" },
      ],
      extraConstructions: [
        { id: "make_i_total", operator: "vector", inputs: { start: "n0", end: "n1" }, outputs: ["i_total"] },
        { id: "make_i_label", operator: "label", inputs: { target: "i_total", text: "I" }, outputs: ["i_label"] },
      ],
      assertions: [
        { id: "series_path", predicate: "path", entities: ["src", "r2"], expected: true, severity: "fatal" },
        { id: "parallel_pair", predicate: "sameTerminalPair", entities: ["r6", "r3"], expected: true, severity: "fatal" },
        { id: "n2_degree", predicate: "degree", entities: ["n2"], expected: 3, severity: "fatal" },
        { id: "one_series_then_split", predicate: "pathCount", entities: ["n0", "n3"], expected: 2, severity: "fatal" },
      ],
    },
  ),

  "current-hard-wheatstone": circuit(
    "A balanced Wheatstone bridge with P=2, Q=3, R=4, S unknown.",
    [
      { id: "n0", x: 0, y: 0 },
      { id: "n1", x: 1, y: 1 },
      { id: "n2", x: 2, y: 0 },
      { id: "n3", x: 1, y: -1 },
      { id: "n4", x: 3, y: 0 },
    ],
    [
      { id: "P", symbol: "resistor", start: "n0", end: "n1", role: "P" },
      { id: "Q", symbol: "resistor", start: "n1", end: "n2", role: "Q" },
      { id: "R", symbol: "resistor", start: "n0", end: "n3", role: "R" },
      { id: "S", symbol: "resistor", start: "n3", end: "n2", role: "S" },
      { id: "G", symbol: "galvanometer", start: "n1", end: "n3", role: "galvanometer" },
      { id: "src", symbol: "battery", start: "n0", end: "n2", role: "source" },
    ],
    {
      connectors: [{ id: "out", start: "n2", end: "n4" }],
      extraEntities: [{ id: "g_label", kind: "label", role: "galvanometer label" }],
      extraConstructions: [
        { id: "make_g_label", operator: "label", inputs: { target: "G", text: "G" }, outputs: ["g_label"] },
      ],
      assertions: [
        { id: "n1_degree", predicate: "degree", entities: ["n1"], expected: 3, severity: "fatal" },
        { id: "bridge_paths", predicate: "pathCount", entities: ["n0", "n2"], expected: 5, severity: "fatal" },
        { id: "g_connected", predicate: "connected", entities: ["G", "P"], expected: true, severity: "fatal" },
      ],
    },
  ),

  "magnetism-easy-straight-wire": scene(
    "A long straight vertical wire carries 5.0 A upward. Find B at 10 cm to the right.",
    [
      { id: "wire_a", kind: "point", role: "wire bottom" },
      { id: "wire_b", kind: "point", role: "wire top" },
      { id: "probe", kind: "point", role: "field point" },
      { id: "origin", kind: "point", role: "wire origin" },
      { id: "wire", kind: "line", role: "straight wire" },
      { id: "current", kind: "vector", role: "current" },
      { id: "loop", kind: "circle", role: "field circle" },
      { id: "field", kind: "vector", role: "B at probe" },
      { id: "radius_dim", kind: "dimension", role: "distance" },
      { id: "b_label", kind: "label", role: "B label" },
    ],
    [
      { id: "make_wire_a", operator: "point", inputs: { x: 0, y: -2, coordinateSpace: "world" }, outputs: ["wire_a"] },
      { id: "make_wire_b", operator: "point", inputs: { x: 0, y: 2, coordinateSpace: "world" }, outputs: ["wire_b"] },
      { id: "make_probe", operator: "point", inputs: { x: 0.1, y: 0, coordinateSpace: "world" }, outputs: ["probe"] },
      { id: "make_origin", operator: "point", inputs: { x: 0, y: 0, coordinateSpace: "world" }, outputs: ["origin"] },
      { id: "make_wire", operator: "line", inputs: { start: "wire_a", end: "wire_b" }, outputs: ["wire"] },
      { id: "make_current", operator: "vector", inputs: { start: "wire_a", end: "wire_b" }, outputs: ["current"] },
      { id: "make_loop", operator: "circle", inputs: { center: "origin", radius: 0.1 }, outputs: ["loop"] },
      { id: "make_field", operator: "vector", inputs: { start: "probe", end: { x: 0.1, y: 0.08, coordinateSpace: "world" } }, outputs: ["field"] },
      { id: "make_radius_dim", operator: "dimension", inputs: { start: "origin", end: "probe" }, outputs: ["radius_dim"] },
      { id: "make_b_label", operator: "label", inputs: { target: "field", text: "B" }, outputs: ["b_label"] },
    ],
    [
      { id: "radius_perp_wire", predicate: "perpendicular", entities: ["radius_dim", "wire"], expected: true, severity: "fatal" },
      { id: "probe_on_loop", predicate: "on", entities: ["probe", "loop"], expected: true, severity: "fatal" },
      { id: "radius_ratio", predicate: "distance_ratio", entities: ["wire_a", "wire_b", "origin", "probe"], expected: 40, severity: "fatal" },
    ],
  ),

  "emi-medium-moving-rod": scene(
    "A conducting rod moves along parallel rails through a uniform magnetic field.",
    [
      { id: "r1a", kind: "point", role: "rail 1 start" },
      { id: "r1b", kind: "point", role: "rail 1 end" },
      { id: "r2a", kind: "point", role: "rail 2 start" },
      { id: "r2b", kind: "point", role: "rail 2 end" },
      { id: "stub", kind: "point", role: "resistor stub" },
      { id: "rail1", kind: "line", role: "rail" },
      { id: "rail2", kind: "segment", role: "rail" },
      { id: "rod", kind: "segment", role: "moving rod" },
      { id: "R", kind: "component", role: "resistor" },
      { id: "lead", kind: "connector", role: "closing wire" },
      { id: "velocity", kind: "vector", role: "rod velocity" },
      { id: "force", kind: "vector", role: "magnetic force" },
      { id: "length_dim", kind: "dimension", role: "rod length" },
      { id: "v_label", kind: "label", role: "velocity" },
    ],
    [
      { id: "make_r1a", operator: "point", inputs: { x: 0, y: 0.6, coordinateSpace: "world" }, outputs: ["r1a"] },
      { id: "make_r1b", operator: "point", inputs: { x: 2, y: 0.6, coordinateSpace: "world" }, outputs: ["r1b"] },
      { id: "make_r2a", operator: "point", inputs: { x: 0, y: 0, coordinateSpace: "world" }, outputs: ["r2a"] },
      { id: "make_r2b", operator: "point", inputs: { x: 2, y: 0, coordinateSpace: "world" }, outputs: ["r2b"] },
      { id: "make_stub", operator: "point", inputs: { x: -0.4, y: 0.3, coordinateSpace: "world" }, outputs: ["stub"] },
      { id: "make_rail1", operator: "line", inputs: { start: "r1a", end: "r1b" }, outputs: ["rail1"] },
      { id: "make_rail2", operator: "segment", inputs: { start: "r2a", end: "r2b" }, outputs: ["rail2"] },
      { id: "make_rod", operator: "segment", inputs: { start: "r1b", end: "r2b" }, outputs: ["rod"] },
      { id: "make_R", operator: "symbol", inputs: { symbol: "resistor", start: "r1a", end: "r2a" }, outputs: ["R"] },
      { id: "make_lead", operator: "connect", inputs: { start: "r1a", end: "stub" }, outputs: ["lead"] },
      { id: "make_velocity", operator: "vector", inputs: { start: "r1b", end: { x: 2.5, y: 0.6, coordinateSpace: "world" } }, outputs: ["velocity"] },
      { id: "make_force", operator: "vector", inputs: { start: "r1b", end: { x: 1.5, y: 0.6, coordinateSpace: "world" } }, outputs: ["force"] },
      { id: "make_length_dim", operator: "dimension", inputs: { start: "r1b", end: "r2b" }, outputs: ["length_dim"] },
      { id: "make_v_label", operator: "label", inputs: { target: "velocity", text: "v" }, outputs: ["v_label"] },
    ],
    [
      { id: "rails_parallel", predicate: "parallel", entities: ["rail1", "rail2"], expected: true, severity: "fatal" },
      { id: "rod_perp", predicate: "perpendicular", entities: ["rod", "rail2"], expected: true, severity: "fatal" },
      { id: "loop_path", predicate: "path", entities: ["R", "lead"], expected: true, severity: "fatal" },
      { id: "force_opposite_v", predicate: "opposite_direction", entities: ["force", "velocity"], expected: true, severity: "fatal" },
      { id: "resistor_connected", predicate: "connected", entities: ["R", "lead"], expected: true, severity: "fatal" },
    ],
  ),

  "ac-hard-series-lcr": circuit(
    "A series LCR circuit connected to an AC source, with a voltage phasor diagram.",
    [
      { id: "n0", x: 0, y: 0 },
      { id: "n1", x: 1, y: 0 },
      { id: "n2", x: 2, y: 0 },
      { id: "n3", x: 3, y: 0 },
      { id: "n4", x: 4, y: 0 },
    ],
    [
      { id: "src", symbol: "ac_source", start: "n0", end: "n1", role: "AC source" },
      { id: "L", symbol: "inductor", start: "n1", end: "n2", role: "inductor" },
      { id: "Rsym", symbol: "resistor", start: "n2", end: "n3", role: "resistor" },
      { id: "Csym", symbol: "capacitor", start: "n3", end: "n4", role: "capacitor" },
    ],
    {
      connectors: [{ id: "return", start: "n4", end: "n0" }],
      extraEntities: [
        { id: "origin", kind: "point", role: "phasor origin" },
        { id: "vr", kind: "vector", role: "VR" },
        { id: "vl", kind: "vector", role: "VL" },
        { id: "vc", kind: "vector", role: "VC" },
        { id: "vlx", kind: "vector", role: "VL x" },
        { id: "vly", kind: "vector", role: "VL y" },
        { id: "phase", kind: "arc", role: "phase angle" },
        { id: "vr_label", kind: "label", role: "VR" },
      ],
      extraConstructions: [
        { id: "make_origin", operator: "point", inputs: { x: 0, y: 2, coordinateSpace: "world" }, outputs: ["origin"] },
        { id: "make_vr", operator: "vector", inputs: { start: "origin", end: { x: 1, y: 2, coordinateSpace: "world" } }, outputs: ["vr"] },
        { id: "make_vl", operator: "vector", inputs: { start: "origin", end: { x: 0, y: 3, coordinateSpace: "world" } }, outputs: ["vl"] },
        { id: "make_vc", operator: "vector", inputs: { start: "origin", end: { x: 0, y: 1.2, coordinateSpace: "world" } }, outputs: ["vc"] },
        { id: "make_components", operator: "vector_components", inputs: { origin: "origin", vector: [2, 0.5], basis: "vr" }, outputs: ["vlx", "vly"] },
        { id: "make_phase", operator: "arc", inputs: { center: "origin", radius: 0.4, startAngle: 0, endAngle: 90, angleUnit: "degrees" }, outputs: ["phase"] },
        { id: "make_vr_label", operator: "label", inputs: { target: "vr", text: "VR" }, outputs: ["vr_label"] },
      ],
      assertions: [
        { id: "series_path", predicate: "path", entities: ["src", "L", "Rsym", "Csym"], expected: true, severity: "fatal" },
        { id: "vl_perp_vr", predicate: "perpendicular", entities: ["vl", "vr"], expected: true, severity: "fatal" },
        { id: "vr_connected", predicate: "connected", entities: ["vr", "origin"], expected: true, severity: "fatal" },
      ],
    },
  ),

  "optics-easy-plane-mirror": scene(
    "A 3 cm tall object is placed 5 cm in front of a plane mirror.",
    [
      { id: "m0", kind: "point", role: "mirror bottom" },
      { id: "m1", kind: "point", role: "mirror top" },
      { id: "obj", kind: "point", role: "object" },
      { id: "hit", kind: "point", role: "incidence" },
      { id: "mirror_line", kind: "line", role: "mirror plane" },
      { id: "mirror", kind: "segment", role: "mirror" },
      { id: "incident", kind: "vector", role: "incident ray" },
      { id: "normal", kind: "vector", role: "normal" },
      { id: "reflected", kind: "ray", role: "reflected ray" },
      { id: "image", kind: "point", role: "image" },
      { id: "u_dim", kind: "dimension", role: "object distance" },
      { id: "obj_label", kind: "label", role: "object" },
      { id: "front", kind: "point", role: "object-side sample" },
    ],
    [
      { id: "make_m0", operator: "point", inputs: { x: 0, y: -3, coordinateSpace: "world" }, outputs: ["m0"] },
      { id: "make_m1", operator: "point", inputs: { x: 0, y: 3, coordinateSpace: "world" }, outputs: ["m1"] },
      { id: "make_obj", operator: "point", inputs: { x: -5, y: 1.5, coordinateSpace: "world" }, outputs: ["obj"] },
      { id: "make_hit", operator: "point", inputs: { x: 0, y: 1.5, coordinateSpace: "world" }, outputs: ["hit"] },
      { id: "make_mirror_line", operator: "line", inputs: { start: "m0", end: "m1" }, outputs: ["mirror_line"] },
      { id: "make_mirror", operator: "segment", inputs: { start: "m0", end: "m1" }, outputs: ["mirror"] },
      { id: "make_incident", operator: "vector", inputs: { start: "obj", end: "hit" }, outputs: ["incident"] },
      { id: "make_normal", operator: "normal_at", inputs: { point: "hit", surface: "mirror" }, outputs: ["normal"] },
      { id: "make_reflected", operator: "reflect_direction", inputs: { origin: "hit", incoming: "incident", normal: "normal" }, outputs: ["reflected"] },
      { id: "make_image", operator: "reflect_point", inputs: { point: "obj", line: "mirror_line" }, outputs: ["image"] },
      { id: "make_u_dim", operator: "dimension", inputs: { start: "obj", end: "hit" }, outputs: ["u_dim"] },
      { id: "make_obj_label", operator: "label", inputs: { target: "obj", text: "O" }, outputs: ["obj_label"] },
      { id: "make_front", operator: "point", inputs: { x: -2, y: 1.5, coordinateSpace: "world" }, outputs: ["front"] },
    ],
    [
      { id: "equal_distance", predicate: "equal_length", entities: ["obj", "hit", "image", "hit"], expected: true, severity: "fatal" },
      { id: "normal_perp", predicate: "perpendicular", entities: ["normal", "mirror"], expected: true, severity: "fatal" },
      { id: "incident_at_hit", predicate: "incident", entities: ["hit", "mirror"], expected: true, severity: "fatal" },
      { id: "object_side", predicate: "same_side", entities: ["obj", "front", "hit"], expected: true, severity: "fatal" },
    ],
  ),

  "optics-medium-concave-mirror": concaveMirrorOracle(),

  "optics-hard-prism-minimum-deviation": scene(
    "A prism of apex 60 degrees and index sqrt(3) at minimum deviation.",
    [
      { id: "A", kind: "point", role: "apex" },
      { id: "B", kind: "point", role: "base left" },
      { id: "C", kind: "point", role: "base right" },
      { id: "prism", kind: "polygon", role: "prism" },
      { id: "face1", kind: "segment", role: "first face" },
      { id: "src", kind: "point", role: "incident origin" },
      { id: "hit", kind: "point", role: "first incidence" },
      { id: "incident", kind: "ray", role: "incident ray" },
      { id: "normal", kind: "vector", role: "face normal" },
      { id: "refracted", kind: "ray", role: "internal ray" },
      { id: "angle_arc", kind: "arc", role: "apex angle" },
      { id: "prism_label", kind: "label", role: "prism" },
    ],
    [
      { id: "make_A", operator: "point", inputs: { x: 0, y: 1.73205080757, coordinateSpace: "world" }, outputs: ["A"] },
      { id: "make_B", operator: "point", inputs: { x: -1, y: 0, coordinateSpace: "world" }, outputs: ["B"] },
      { id: "make_C", operator: "point", inputs: { x: 1, y: 0, coordinateSpace: "world" }, outputs: ["C"] },
      { id: "make_prism", operator: "polygon", inputs: { points: ["A", "B", "C"] }, outputs: ["prism"] },
      { id: "make_face1", operator: "segment", inputs: { start: "A", end: "B" }, outputs: ["face1"] },
      { id: "make_src", operator: "point", inputs: { x: -2, y: 0.86602540378, coordinateSpace: "world" }, outputs: ["src"] },
      { id: "make_hit", operator: "surface_intersection", inputs: { origin: "src", through: { x: 0, y: 0.86602540378, coordinateSpace: "world" }, surface: "face1" }, outputs: ["hit"] },
      { id: "make_incident", operator: "ray", inputs: { start: "src", end: "hit" }, outputs: ["incident"] },
      { id: "make_normal", operator: "normal_at", inputs: { point: "hit", surface: "face1" }, outputs: ["normal"] },
      { id: "make_refracted", operator: "refract_direction", inputs: { origin: "hit", incoming: "incident", normal: "normal", n1: 1, n2: 1.73205080757 }, outputs: ["refracted"] },
      { id: "make_angle_arc", operator: "arc", inputs: { center: "A", radius: 0.3, startAngle: 240, endAngle: 300, angleUnit: "degrees" }, outputs: ["angle_arc"] },
      { id: "make_prism_label", operator: "label", inputs: { target: "prism", text: "ABC" }, outputs: ["prism_label"] },
    ],
    [
      { id: "incident_on_face", predicate: "incident", entities: ["hit", "face1"], expected: true, severity: "fatal" },
      { id: "hit_on_face", predicate: "on", entities: ["hit", "face1"], expected: true, severity: "fatal" },
      { id: "isosceles", predicate: "equal_length", entities: ["A", "B", "A", "C"], expected: true, severity: "fatal" },
    ],
  ),

  "modern-easy-photoelectric": energyDiagram(
    "Light of photon energy 3.0 eV falls on a metal of work function 2.0 eV.",
    [
      { id: "vacuum", y: 3, label: "vacuum" },
      { id: "fermi", y: 1, label: "Ef" },
    ],
    { from: "vacuum", to: "fermi" },
  ),

  "modern-medium-hydrogen-transition": energyDiagram(
    "An electron in hydrogen falls from n = 3 to n = 2.",
    [
      { id: "n3", y: 3, label: "n=3" },
      { id: "n2", y: 2, label: "n=2" },
    ],
    { from: "n3", to: "n2" },
  ),

  "modern-hard-zener-regulator": circuit(
    "A 12 V supply feeds a series resistor and a 6.0 V Zener in parallel with a load.",
    [
      { id: "n0", x: 0, y: 0 },
      { id: "n1", x: 1, y: 0 },
      { id: "n2", x: 2, y: 0 },
      { id: "n3", x: 2, y: -1 },
      { id: "n4", x: 2, y: -2 },
    ],
    [
      { id: "src", symbol: "battery", start: "n0", end: "n1", role: "supply" },
      { id: "Rs", symbol: "resistor", start: "n1", end: "n2", role: "series resistor" },
      { id: "Z", symbol: "zener", start: "n2", end: "n3", role: "zener" },
      { id: "RL", symbol: "resistor", start: "n2", end: "n3", role: "load" },
    ],
    {
      connectors: [{ id: "gnd", start: "n3", end: "n4" }],
      extraEntities: [
        { id: "i_load", kind: "vector", role: "load current" },
        { id: "i_label", kind: "label", role: "current" },
      ],
      extraConstructions: [
        { id: "make_i_load", operator: "vector", inputs: { start: "n2", end: "n3" }, outputs: ["i_load"] },
        { id: "make_i_label", operator: "label", inputs: { target: "i_load", text: "IL" }, outputs: ["i_label"] },
      ],
      assertions: [
        { id: "series_path", predicate: "path", entities: ["src", "Rs"], expected: true, severity: "fatal" },
        { id: "parallel_load", predicate: "sameTerminalPair", entities: ["Z", "RL"], expected: true, severity: "fatal" },
        { id: "n2_degree", predicate: "degree", entities: ["n2"], expected: 3, severity: "fatal" },
        { id: "paths_to_ground", predicate: "pathCount", entities: ["n1", "n3"], expected: 2, severity: "fatal" },
      ],
    },
  ),
};
