"use client";

import { jsPDF } from "jspdf";

export interface NotesEpoch {
  index: number;
  snapshotDataUrl: string;
  narrationText: string;
  timestampMs: number;
}

export interface ExportNotesParams {
  title: string;
  epochs: NotesEpoch[];
}

const PAGE_MARGIN_PT = 40;
const SECTION_GAP_PT = 16;
const IMAGE_GAP_PT = 12;
const BOARD_ASPECT = 1200 / 700;

function sanitizeFilename(title: string): string {
  const base = title.trim() || "lecture-notes";
  return base.replace(/[^a-z0-9-_ ]/gi, "").replace(/\s+/g, "-").toLowerCase();
}

function formatDate(): string {
  return new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

export function exportNotesPdf({ title, epochs }: ExportNotesParams): void {
  const doc = new jsPDF({ orientation: "portrait", unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const contentWidth = pageWidth - PAGE_MARGIN_PT * 2;
  const maxImageHeight = pageHeight * 0.45;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  const titleLines = doc.splitTextToSize(title || "Lecture Notes", contentWidth);
  doc.text(titleLines, PAGE_MARGIN_PT, PAGE_MARGIN_PT + 8);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(110);
  const subtitle = `${formatDate()}  \u2022  Generated by HeyTutor  \u2022  ${epochs.length} section${epochs.length === 1 ? "" : "s"}`;
  doc.text(subtitle, PAGE_MARGIN_PT, PAGE_MARGIN_PT + 30);
  doc.setTextColor(0);

  let cursorY = PAGE_MARGIN_PT + 60;

  epochs.forEach((epoch, i) => {
    const sectionTitle = `Part ${i + 1}`;

    const sectionHeaderHeight = 24;
    if (cursorY + sectionHeaderHeight > pageHeight - PAGE_MARGIN_PT) {
      doc.addPage();
      cursorY = PAGE_MARGIN_PT;
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(40);
    doc.text(sectionTitle, PAGE_MARGIN_PT, cursorY);
    doc.setTextColor(0);
    cursorY += sectionHeaderHeight;

    const imageWidth = contentWidth;
    const imageHeight = imageWidth / BOARD_ASPECT;
    const fittedImageHeight = Math.min(imageHeight, maxImageHeight);
    const fittedImageWidth = fittedImageHeight * BOARD_ASPECT;
    const imageX = PAGE_MARGIN_PT + (contentWidth - fittedImageWidth) / 2;

    if (cursorY + fittedImageHeight + IMAGE_GAP_PT > pageHeight - PAGE_MARGIN_PT) {
      doc.addPage();
      cursorY = PAGE_MARGIN_PT;
    }

    try {
      doc.addImage(
        epoch.snapshotDataUrl,
        "PNG",
        imageX,
        cursorY,
        fittedImageWidth,
        fittedImageHeight,
        undefined,
        "FAST",
      );
    } catch {
      doc.setFont("helvetica", "italic");
      doc.setFontSize(10);
      doc.setTextColor(150);
      doc.text("[board image unavailable]", PAGE_MARGIN_PT, cursorY + 14);
      doc.setTextColor(0);
    }
    cursorY += fittedImageHeight + IMAGE_GAP_PT;

    if (epoch.narrationText.trim()) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.setTextColor(50);
      const narrationLines = doc.splitTextToSize(epoch.narrationText.trim(), contentWidth);
      const lineHeight = 14;
      for (const line of narrationLines) {
        if (cursorY + lineHeight > pageHeight - PAGE_MARGIN_PT) {
          doc.addPage();
          cursorY = PAGE_MARGIN_PT;
        }
        doc.text(line, PAGE_MARGIN_PT, cursorY);
        cursorY += lineHeight;
      }
      doc.setTextColor(0);
    }

    cursorY += SECTION_GAP_PT;
  });

  doc.save(`${sanitizeFilename(title)}.pdf`);
}
