"use client";

import { jsPDF } from "jspdf";
import { pdfSafeText, type NotesPdfSection } from "@/features/tutor-session/lib/notesPdf";

export interface NotesEpoch {
  index: number;
  /** Question whose ink was on the board when the page was captured. */
  question: string;
  snapshotDataUrl: string;
  /** Narration spoken while this page was on the board. */
  narrationText: string;
  timestampMs: number;
}

export interface ExportNotesParams {
  title: string;
  sections: NotesPdfSection[];
}

type TextStyle = {
  font: "helvetica" | "courier";
  weight: "normal" | "bold" | "italic";
  size: number;
  gray: number;
  indent?: number;
};

const PAGE_MARGIN_PT = 40;
const SECTION_GAP_PT = 22;
const IMAGE_GAP_PT = 12;
const BOARD_ASPECT = 1200 / 700;
const LINE_HEIGHT_FACTOR = 1.4;

const EYEBROW: TextStyle = { font: "helvetica", weight: "bold", size: 9.5, gray: 120 };
const QUESTION: TextStyle = { font: "helvetica", weight: "bold", size: 13, gray: 20 };
const FACTS: TextStyle = { font: "helvetica", weight: "normal", size: 9.5, gray: 110 };
const WORK_LINE: TextStyle = { font: "courier", weight: "normal", size: 10.5, gray: 30, indent: 10 };
const NARRATION: TextStyle = { font: "helvetica", weight: "normal", size: 10.5, gray: 50 };
const PLACEHOLDER: TextStyle = { font: "helvetica", weight: "italic", size: 10, gray: 150 };

function sanitizeFilename(title: string): string {
  const base = title.trim() || "lecture-notes";
  return base.replace(/[^a-z0-9-_ ]/gi, "").replace(/\s+/g, "-").toLowerCase();
}

function formatDate(): string {
  return new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

export function exportNotesPdf({ title, sections }: ExportNotesParams): void {
  const doc = new jsPDF({ orientation: "portrait", unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const contentWidth = pageWidth - PAGE_MARGIN_PT * 2;
  const bottomY = pageHeight - PAGE_MARGIN_PT;
  const maxImageHeight = pageHeight * 0.45;
  let cursorY = PAGE_MARGIN_PT;

  const ensureSpace = (height: number) => {
    if (cursorY + height > bottomY) {
      doc.addPage();
      cursorY = PAGE_MARGIN_PT;
    }
  };

  const writeText = (text: string, style: TextStyle) => {
    const safe = pdfSafeText(text).replace(/\s+/g, " ").trim();
    if (!safe) return;
    doc.setFont(style.font, style.weight);
    doc.setFontSize(style.size);
    doc.setTextColor(style.gray);
    const indent = style.indent ?? 0;
    const lines = doc.splitTextToSize(safe, contentWidth - indent) as string[];
    const lineHeight = style.size * LINE_HEIGHT_FACTOR;
    for (const line of lines) {
      ensureSpace(lineHeight);
      doc.text(line, PAGE_MARGIN_PT + indent, cursorY + style.size);
      cursorY += lineHeight;
    }
  };

  const writeImage = (dataUrl: string) => {
    const naturalHeight = contentWidth / BOARD_ASPECT;
    const fittedHeight = Math.min(naturalHeight, maxImageHeight);
    const fittedWidth = fittedHeight * BOARD_ASPECT;
    const imageX = PAGE_MARGIN_PT + (contentWidth - fittedWidth) / 2;
    cursorY += IMAGE_GAP_PT;
    ensureSpace(fittedHeight + IMAGE_GAP_PT);
    try {
      doc.addImage(dataUrl, "PNG", imageX, cursorY, fittedWidth, fittedHeight, undefined, "FAST");
      cursorY += fittedHeight + IMAGE_GAP_PT;
    } catch {
      writeText("[board image unavailable]", PLACEHOLDER);
    }
  };

  writeText(title || "Lecture Notes", { font: "helvetica", weight: "bold", size: 22, gray: 0 });
  cursorY += 4;
  const count = sections.length;
  writeText(
    `${formatDate()}  ·  Generated by HeyTutor  ·  ${count} question${count === 1 ? "" : "s"}`,
    { font: "helvetica", weight: "normal", size: 10.5, gray: 110 },
  );
  cursorY += 18;

  sections.forEach((section, index) => {
    if (index > 0) cursorY += SECTION_GAP_PT;
    // Keep a heading with at least a line of its body on the same page.
    ensureSpace(64);

    writeText(
      section.interrupted
        ? `Question ${index + 1}  (lesson stopped early)`
        : `Question ${index + 1}`,
      EYEBROW,
    );
    writeText(section.question || "Untitled question", QUESTION);
    if (section.planFacts.length > 0) {
      cursorY += 2;
      writeText(`Values: ${section.planFacts.join("   ")}`, FACTS);
    }

    for (const image of section.images) {
      writeImage(image);
    }

    if (section.workLines.length > 0) {
      cursorY += 6;
      writeText("Board work", EYEBROW);
      cursorY += 2;
      for (const line of section.workLines) {
        writeText(line, WORK_LINE);
      }
    }

    if (section.narration) {
      cursorY += 8;
      writeText("Explanation", EYEBROW);
      cursorY += 2;
      writeText(section.narration, NARRATION);
    }
  });

  doc.save(`${sanitizeFilename(title)}.pdf`);
}
