import { registerModelAdmission, type InputRole, type ModelAdmission } from "./admission";

const role = (name: string, unit: string): InputRole => ({ role: name, unit });
const dim = (name: string): InputRole => role(name, "1");
const categorical = (name: string, values: Readonly<Record<string, readonly string[]>>): InputRole => ({ role: name, unit: "1", sourcePhrases: values });
const flag = (name: string, phrase: string): InputRole => categorical(name, { "1": [phrase] });
const finite = (v: Readonly<Record<string, number>>, key: string): number => {
  const value = v[key];
  if (typeof value !== "number" || !Number.isFinite(value)) throw new Error(`${key} must be finite`);
  return value;
};
const positive = (v: Readonly<Record<string, number>>, key: string): number => {
  const value = finite(v, key);
  if (!(value > 0)) throw new Error(`${key} must be positive`);
  return value;
};
const optional = (v: Readonly<Record<string, number>>, key: string): number | undefined => v[key] === undefined ? undefined : finite(v, key);
const integer = (value: number, key: string): number => {
  if (!Number.isInteger(value)) throw new Error(`${key} must be an integer`);
  return value;
};
const add = (admission: Omit<ModelAdmission, "resultKind"> & { resultKind?: ModelAdmission["resultKind"] }): void => registerModelAdmission(admission);

add({ name: "mf.wire", roles: { mu0: role("magnetic permeability", "H/m"), I: role("signed wire current", "A"), d: role("signed transverse distance", "m") }, optionalRoles: { start: role("finite wire start coordinate", "m"), end: role("finite wire end coordinate", "m"), atX: role("observation axial coordinate", "m"), amperian: flag("Amperian-path declaration", "circular Amperian path"), externalI: role("exterior signed current", "A"), externalRadius: role("exterior current radius", "m") }, optionalGroups: [["start", "end"], ["externalI", "externalRadius"]], assumptions: ["straight wire", "signed transverse distance"], scalar(v): Record<string, number> {
  const mu0 = positive(v, "mu0"), I = finite(v, "I"), d = finite(v, "d"); if (d === 0) throw new Error("wire coincidence");
  const start = optional(v, "start"), end = optional(v, "end"), atX = optional(v, "atX") ?? 0, amperian = optional(v, "amperian") ?? 0;
  if (start !== undefined && end !== undefined) { if (!(start < end) || amperian !== 0) throw new Error("invalid finite wire"); return { B: mu0 * I / (4 * Math.PI * d) * ((end - atX) / Math.hypot(end - atX, d) - (start - atX) / Math.hypot(start - atX, d)) }; }
  if (amperian === 1) { if (!(d > 0)) throw new Error("Amperian radius must be positive"); const externalI = optional(v, "externalI") ?? 0, externalRadius = optional(v, "externalRadius"); if (externalRadius !== undefined && !(externalRadius > d)) throw new Error("exterior current must stay outside"); return { B: mu0 / (2 * Math.PI) * (I / d - (externalRadius === undefined ? 0 : externalI / (externalRadius - d))), circulation: mu0 * I }; }
  return { B: mu0 * I / (2 * Math.PI * d) };
} });

add({ name: "mf.arc", roles: { mu0: role("magnetic permeability", "H/m"), I: role("signed arc current", "A"), delta: role("signed arc angle", "rad"), R: role("arc radius", "m") }, optionalRoles: { startAngle: role("arc start angle", "rad"), startLead: role("start radial lead radius", "m"), endLead: role("end radial lead radius", "m") }, optionalGroups: [["startLead", "endLead"]], assumptions: ["circular arc", "observation at the centre"], scalar(v) { const delta = finite(v, "delta"), R = positive(v, "R"); if (delta === 0 || Math.abs(delta) > 2 * Math.PI) throw new Error("invalid arc angle"); for (const key of ["startLead", "endLead"]) { const lead = optional(v, key); if (lead !== undefined && (!(lead > 0) || lead === R || Math.abs(delta) === 2 * Math.PI)) throw new Error("invalid radial lead"); } return { B: positive(v, "mu0") * finite(v, "I") * delta / (4 * Math.PI * R) }; } });
add({ name: "mf.loop", roles: { mu0: role("magnetic permeability", "H/m"), I: role("signed loop current", "A"), R: role("loop radius", "m"), x: role("signed axial coordinate", "m") }, optionalRoles: { N: dim("turn count"), axisAngle: role("loop axis angle", "rad") }, assumptions: ["circular coil", "axial observation"], scalar(v) { const R = positive(v, "R"), N = integer(optional(v, "N") ?? 1, "N"); if (N <= 0) throw new Error("turn count must be positive"); return { B: positive(v, "mu0") * N * finite(v, "I") * R * R / (2 * (R * R + finite(v, "x") ** 2) ** 1.5) }; } });
add({ name: "mf.solenoid", roles: { mu0: role("magnetic permeability", "H/m"), n: role("turn density", "per m"), I: role("signed solenoid current", "A"), interior: categorical("field-region declaration", { "0": ["exterior of the solenoid"], "1": ["interior of the solenoid"], "2": ["end of a semi-infinite solenoid"] }) }, assumptions: ["ideal long solenoid"], scalar(v) { const selector = finite(v, "interior"); if (![0, 1, 2].includes(selector)) throw new Error("invalid field region"); return { B: positive(v, "mu0") * positive(v, "n") * finite(v, "I") * (selector === 0 ? 0 : selector === 2 ? 0.5 : 1) }; } });
add({ name: "mf.toroid", roles: { mu0: role("magnetic permeability", "H/m"), N: dim("turn count"), I: role("signed toroid current", "A"), a: role("inner radius", "m"), b: role("outer radius", "m"), r: role("observation radius", "m") }, optionalRoles: { ideal: flag("ideal continuous-winding declaration", "ideal continuously wound toroid") }, assumptions: ["toroid", "radial observation"], scalar(v) { const a = positive(v, "a"), b = positive(v, "b"), r = finite(v, "r"), N = integer(positive(v, "N"), "N"); if (!(b > a) || r < 0 || r === a || r === b) throw new Error("invalid toroid radii"); if (r <= a || r >= b) { if (optional(v, "ideal") !== 1) throw new Error("exterior field requires ideal declaration"); return { B: 0 }; } return { B: positive(v, "mu0") * N * finite(v, "I") / (2 * Math.PI * r) }; } });

add({ name: "mm.lines", roles: { mx: role("magnetic moment x component", "A m^2"), my: role("magnetic moment y component", "A m^2") }, assumptions: ["bar magnet field-line representation"], resultKind: "representation", scalar(v) { if (Math.hypot(finite(v, "mx"), finite(v, "my")) === 0) throw new Error("moment must be nonzero"); return {}; } });
add({ name: "mm.equivalent", roles: { N: dim("turn count"), I: role("signed winding current", "A"), A: role("loop area", "m^2") }, assumptions: ["far-field magnetic-moment correspondence"], scalar(v) { return { m: positive(v, "N") * finite(v, "I") * positive(v, "A") }; } });
add({ name: "mm.dipole", roles: { mu0: role("magnetic permeability", "H/m"), m: role("signed magnetic moment", "A m^2"), r: role("observation distance", "m"), axial: categorical("observation-axis declaration", { "0": ["equatorial observation"], "1": ["axial observation"] }) }, optionalRoles: { poleHalfSeparation: role("pole half-separation", "m") }, assumptions: ["magnetic dipole", "declared axial or equatorial observation"], scalar(v) { const mu0 = positive(v, "mu0"), m = finite(v, "m"), r = positive(v, "r"), axial = finite(v, "axial"); if (axial !== 0 && axial !== 1) throw new Error("invalid axis selector"); const a = optional(v, "poleHalfSeparation"); if (a !== undefined) { if (!(a > 0) || (axial === 1 && !(r > a))) throw new Error("invalid finite pole geometry"); return { B: axial === 1 ? mu0 * m / (8 * Math.PI * a) * (1 / (r - a) ** 2 - 1 / (r + a) ** 2) : -mu0 * m / (4 * Math.PI * (r * r + a * a) ** 1.5) }; } return { B: mu0 * (axial === 1 ? 2 : -1) * m / (4 * Math.PI * r ** 3) }; } });
add({ name: "mm.earth", roles: { Bh: role("horizontal magnetic-field magnitude", "T"), Bv: role("signed downward vertical field", "T") }, optionalRoles: { declination: role("east-positive declination", "rad"), northX: dim("true-north x component"), northY: dim("true-north y component") }, optionalGroups: [["declination", "northX", "northY"]], assumptions: ["local magnetic field", "vertical component positive down"], scalar(v) { const Bh = finite(v, "Bh"), Bv = finite(v, "Bv"); if (Bh < 0 || Math.hypot(Bh, Bv) === 0) throw new Error("invalid local field"); const result: Record<string, number> = { B: Math.hypot(Bh, Bv), dip: Math.atan2(Bv, Bh) }; const declination = optional(v, "declination"); if (declination !== undefined) { if (!(Bh > 0) || Math.hypot(finite(v, "northX"), finite(v, "northY")) === 0) throw new Error("declination needs a horizontal reference"); result.declination = declination; } return result; } });
add({ name: "mm.materials", roles: { shown: flag("magnetic-material representation declaration", "magnetic material response") }, optionalRoles: { kind: categorical("material response kind", { "-1": ["diamagnetic"], "1": ["paramagnetic"], "2": ["ferromagnetic"] }), T1: role("first observed temperature", "K"), chi1: dim("first observed susceptibility"), T2: role("second observed temperature", "K"), chi2: dim("second observed susceptibility"), T3: role("third observed temperature", "K"), chi3: dim("third observed susceptibility"), Tc: role("declared Curie temperature", "K") }, optionalGroups: [["T1", "chi1", "T2", "chi2"], ["T3", "chi3"]], assumptions: ["source-supplied magnetic response"], resultKind: "representation", scalar(v) { if (finite(v, "shown") !== 1) throw new Error("representation selector must be one"); const kind = optional(v, "kind"); if (kind !== undefined && ![-1, 1, 2].includes(kind)) throw new Error("invalid material kind"); const T1 = optional(v, "T1"), T2 = optional(v, "T2"), T3 = optional(v, "T3"); if (T1 !== undefined && (!(T1 > 0) || !(T2! > T1) || (T3 !== undefined && !(T3 > T2!)))) throw new Error("temperatures must increase"); for (const key of ["chi1", "chi2", "chi3"]) { const chi = optional(v, key); if (chi !== undefined && ((kind === -1 && !(chi < 0)) || (kind !== -1 && chi < 0))) throw new Error("susceptibility sign disagrees with kind"); } const Tc = optional(v, "Tc"); if (Tc !== undefined && !(Tc > 0)) throw new Error("Tc must be positive"); return {}; } });

add({ name: "mf.lorentz", roles: { q: role("signed particle charge", "C"), vx: role("velocity x component", "m/s"), vy: role("velocity y component", "m/s"), vz: role("velocity z component", "m/s"), Bx: role("magnetic-field x component", "T"), By: role("magnetic-field y component", "T"), Bz: role("magnetic-field z component", "T") }, optionalRoles: { Ex: role("electric-field x component", "V/m"), Ey: role("electric-field y component", "V/m"), Ez: role("electric-field z component", "V/m") }, optionalGroups: [["Ex", "Ey", "Ez"]], assumptions: ["uniform electromagnetic fields"], scalar(v) { const q = finite(v, "q"), vx = finite(v, "vx"), vy = finite(v, "vy"), vz = finite(v, "vz"), Bx = finite(v, "Bx"), By = finite(v, "By"), Bz = finite(v, "Bz"); const Fx = q * ((optional(v, "Ex") ?? 0) + vy * Bz - vz * By), Fy = q * ((optional(v, "Ey") ?? 0) + vz * Bx - vx * Bz), Fz = q * ((optional(v, "Ez") ?? 0) + vx * By - vy * Bx); return { Fx, Fy, Fz, F: Math.hypot(Fx, Fy, Fz) }; } });
add({ name: "mf.selector", roles: { E: role("signed electric field", "V/m"), B: role("signed magnetic field", "T"), crossed: flag("crossed-field declaration", "crossed electric and magnetic fields") }, optionalRoles: { q: role("signed beam charge", "C"), vx: role("signed beam velocity", "m/s") }, assumptions: ["uniform crossed fields"], scalar(v) { const E = finite(v, "E"), B = finite(v, "B"); if (E === 0 || B === 0 || finite(v, "crossed") !== 1 || (optional(v, "q") ?? 1) === 0) throw new Error("invalid selector"); const speed = E / B, vx = optional(v, "vx"); if (vx !== undefined && Math.abs(E - vx * B) > 1e-9 * Math.max(1, Math.abs(E))) throw new Error("unbalanced beam"); return { v: speed }; } });
add({ name: "mf.cyclotron", roles: { q: role("signed particle charge", "C"), m: role("particle mass", "kg"), B: role("signed magnetic field", "T"), v: role("particle speed", "m/s") }, optionalRoles: { timing: flag("timing-result declaration", "cyclotron period and frequency"), gapVoltage: role("cyclotron gap voltage", "V"), crossing: dim("gap crossing index"), rfSign: categorical("signed RF polarity", { "-1": ["negative RF polarity"], "1": ["positive RF polarity"] }) }, optionalGroups: [["gapVoltage", "crossing"]], assumptions: ["nonrelativistic cyclotron", "uniform magnetic field"], scalar(v) { const q = finite(v, "q"), m = positive(v, "m"), B = finite(v, "B"), speed = positive(v, "v"); if (q === 0 || B === 0) throw new Error("cyclotron needs charge and field"); const result: Record<string, number> = { radius: m * speed / Math.abs(q * B) }; if (optional(v, "timing") === 1) { result.period = 2 * Math.PI * m / Math.abs(q * B); result.frequency = Math.abs(q * B) / (2 * Math.PI * m); } const voltage = optional(v, "gapVoltage"), crossing = optional(v, "crossing"); if (voltage !== undefined && crossing !== undefined) { if (!(voltage > 0) || integer(crossing, "crossing") < 0) throw new Error("invalid gap declaration"); const required = Math.sign(q) * (-1) ** crossing, rf = optional(v, "rfSign"); if (rf !== undefined && rf !== required) throw new Error("wrong RF polarity"); result.gapEnergy = Math.abs(q) * voltage; } else if (optional(v, "rfSign") !== undefined) throw new Error("RF polarity needs a gap declaration"); return result; } });
add({ name: "mf.helix", roles: { m: role("particle mass", "kg"), q: role("signed particle charge", "C"), B: role("signed magnetic field", "T"), vPerp: role("perpendicular speed", "m/s"), vPar: role("signed parallel velocity", "m/s") }, assumptions: ["uniform magnetic field", "world z field axis"], scalar(v) { const m = positive(v, "m"), q = finite(v, "q"), B = finite(v, "B"), perpendicular = positive(v, "vPerp"); if (q === 0 || B === 0) throw new Error("helix needs charge and field"); const period = 2 * Math.PI * m / Math.abs(q * B); return { radius: m * perpendicular / Math.abs(q * B), pitch: finite(v, "vPar") * period }; } });
add({ name: "mf.conductor", roles: { I: role("signed conductor current", "A"), Lx: role("length-vector x component", "m"), Ly: role("length-vector y component", "m"), Lz: role("length-vector z component", "m"), Bx: role("magnetic-field x component", "T"), By: role("magnetic-field y component", "T"), Bz: role("magnetic-field z component", "T") }, assumptions: ["straight current-carrying conductor", "uniform magnetic field"], scalar(v) { const I = finite(v, "I"), Lx = finite(v, "Lx"), Ly = finite(v, "Ly"), Lz = finite(v, "Lz"), Bx = finite(v, "Bx"), By = finite(v, "By"), Bz = finite(v, "Bz"); if (Math.hypot(Lx, Ly, Lz) === 0 || Lz !== 0) throw new Error("unsupported conductor vector"); return { Fx: I * (Ly * Bz - Lz * By), Fy: I * (Lz * Bx - Lx * Bz), Fz: I * (Lx * By - Ly * Bx) }; } });
add({ name: "mf.parallel", roles: { mu0: role("magnetic permeability", "H/m"), I1: role("first signed wire current", "A"), I2: role("second signed wire current", "A"), d: role("wire separation", "m"), length: role("declared wire length", "m") }, assumptions: ["parallel straight conductors"], scalar(v) { const product = finite(v, "I1") * finite(v, "I2"); return { perLength: positive(v, "mu0") * product / (2 * Math.PI * positive(v, "d")), attract: product > 0 ? 1 : 0 }; } });
add({ name: "mf.ampere", roles: { stated: flag("definition statement declaration", "definition of the ampere") }, optionalRoles: { currentSI: flag("current-SI definition declaration", "current SI definition") }, assumptions: ["definition recall"], resultKind: "representation", scalar(v): Record<string, number> { if (finite(v, "stated") !== 1 || ![undefined, 1].includes(optional(v, "currentSI"))) throw new Error("definition declaration is invalid"); return {}; } });
add({ name: "mf.loop_torque", roles: { I: role("signed loop current", "A"), Ax: role("area-vector x component", "m^2"), Ay: role("area-vector y component", "m^2"), Az: role("area-vector z component", "m^2"), Bx: role("magnetic-field x component", "T"), By: role("magnetic-field y component", "T"), Bz: role("magnetic-field z component", "T") }, optionalRoles: { N: dim("turn count") }, assumptions: ["planar current loop", "uniform magnetic field"], scalar(v) { const scale = finite(v, "I") * integer(optional(v, "N") ?? 1, "N"), Ax = finite(v, "Ax"), Ay = finite(v, "Ay"), Az = finite(v, "Az"), Bx = finite(v, "Bx"), By = finite(v, "By"), Bz = finite(v, "Bz"); if (Math.hypot(Ax, Ay, Az) === 0) throw new Error("area vector must be nonzero"); const taux = scale * (Ay * Bz - Az * By), tauy = scale * (Az * Bx - Ax * Bz), tauz = scale * (Ax * By - Ay * Bx); return { taux, tauy, tauz, tau: Math.hypot(taux, tauy, tauz) }; } });
add({ name: "mf.dipole_moment", roles: { I: role("signed loop current", "A"), A: role("loop area", "m^2") }, optionalRoles: { N: dim("turn count"), nx: dim("normal x component"), ny: dim("normal y component"), nz: dim("normal z component") }, optionalGroups: [["nx", "ny", "nz"]], assumptions: ["planar current loop"], scalar(v): Record<string, number> { const N = integer(optional(v, "N") ?? 1, "N"), m = N * finite(v, "I") * positive(v, "A"); const nx = optional(v, "nx"); if (nx === undefined) return { m }; const ny = finite(v, "ny"), nz = finite(v, "nz"); if (Math.abs(Math.hypot(nx, ny, nz) - 1) > 1e-9) throw new Error("normal must be unit length"); return { m, mx: m * nx, my: m * ny, mz: m * nz }; } });
add({ name: "mf.revolving", roles: { q: role("signed revolving charge", "C"), v: role("orbital speed", "m/s"), r: role("orbit radius", "m") }, optionalRoles: { period: role("orbital period", "s"), direction: categorical("signed orbit direction", { "-1": ["clockwise orbit"], "1": ["counterclockwise orbit"] }), mass: role("particle mass", "kg") }, assumptions: ["circular revolving charge"], scalar(v) { const q = finite(v, "q"), speed = positive(v, "v"), r = positive(v, "r"), direction = optional(v, "direction") ?? 1; if (direction !== 1 && direction !== -1) throw new Error("direction must be signed one"); const result: Record<string, number> = { m: q * direction * speed * r / 2 }; const period = optional(v, "period"); if (period !== undefined) { if (!(period > 0) || Math.abs(speed - 2 * Math.PI * r / period) > 1e-9 * Math.max(1, speed)) throw new Error("period disagrees with speed"); result.I = direction * q / period; } const mass = optional(v, "mass"); if (mass !== undefined) result.L = direction * positive(v, "mass") * speed * r; return result; } });
add({ name: "mf.galvanometer", roles: { N: dim("coil turn count"), I: role("signed coil current", "A"), A: role("coil area", "m^2"), B: role("radial magnetic field", "T"), k: role("torsion constant", "N m/rad") }, optionalRoles: { G: role("galvanometer resistance", "ohm") }, assumptions: ["linear radial-field moving-coil galvanometer"], scalar(v) { const N = positive(v, "N"), I = finite(v, "I"), A = positive(v, "A"), B = finite(v, "B"), k = positive(v, "k"), theta = N * B * A * I / k; if (Math.abs(theta) > Math.PI / 2) throw new Error("linear deflection exceeded"); const result: Record<string, number> = { theta }; const G = optional(v, "G"); if (G !== undefined) { result.currentSensitivity = N * B * A / k; result.voltageSensitivity = result.currentSensitivity / positive(v, "G"); } return result; } });
add({ name: "mf.shunt", roles: { G: role("galvanometer resistance", "ohm"), Ig: role("galvanometer full-scale current", "A"), I: role("ammeter range current", "A") }, assumptions: ["parallel shunt conversion"], scalar(v) { const G = positive(v, "G"), Ig = positive(v, "Ig"), I = positive(v, "I"); if (!(I > Ig)) throw new Error("range must exceed galvanometer current"); return { S: G * Ig / (I - Ig) }; } });
add({ name: "mf.voltmeter", roles: { V: role("voltmeter range voltage", "V"), Ig: role("galvanometer full-scale current", "A"), G: role("galvanometer resistance", "ohm") }, assumptions: ["series multiplier conversion"], scalar(v) { const R = positive(v, "V") / positive(v, "Ig") - positive(v, "G"); if (!(R > 0)) throw new Error("multiplier must be positive"); return { R }; } });
add({ name: "mf.dipole_torque", roles: { mx: role("magnetic-moment x component", "A m^2"), my: role("magnetic-moment y component", "A m^2"), mz: role("magnetic-moment z component", "A m^2"), Bx: role("magnetic-field x component", "T"), By: role("magnetic-field y component", "T"), Bz: role("magnetic-field z component", "T") }, optionalRoles: { energy: flag("potential-energy result declaration", "magnetic potential energy") }, assumptions: ["supplied magnetic moment", "uniform magnetic field"], scalar(v) { const mx = finite(v, "mx"), my = finite(v, "my"), mz = finite(v, "mz"), Bx = finite(v, "Bx"), By = finite(v, "By"), Bz = finite(v, "Bz"); if (Math.hypot(mx, my, mz) === 0) throw new Error("moment must be nonzero"); const result: Record<string, number> = { taux: my * Bz - mz * By, tauy: mz * Bx - mx * Bz, tauz: mx * By - my * Bx }; if (optional(v, "energy") === 1) result.U = -(mx * Bx + my * By + mz * Bz); return result; } });
