/** Actual application hook + installed Next cache construction + Webpack defaults; no compiler/server. */
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import ts from "typescript";
import type { NextConfig } from "next";
import type { NextConfigComplete } from "next/dist/server/config-shared";
import type { webpack } from "next/dist/compiled/webpack/webpack";
import getBaseWebpackConfig from "next/dist/build/webpack-config";
import { defaultConfig } from "next/dist/server/config-shared";
import { trace } from "next/dist/trace";

const app = path.resolve(import.meta.dirname, "../..");
const configFile = path.join(app, "next.config.ts");
const requireApp = createRequire(path.join(app, "package.json"));
type FilesystemCache = Extract<NonNullable<webpack.Configuration["cache"]>, { type: "filesystem" }>;
type HookContext = Parameters<NonNullable<NextConfig["webpack"]>>[1];

// Only the external Sentry build boundary is inert. Evaluate the entire actual
// config, including local imports, so this cannot silently test a copied hook.
function applicationConfig(): NextConfig {
  const source = process.env.NEXT_DEV_CACHE_CONFIG_SOURCE ?? configFile;
  const output = ts.transpileModule(readFileSync(source, "utf8"), {
    compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022, esModuleInterop: true },
  }).outputText;
  const mod = { exports: {} as { default: NextConfig } };
  new Function("require", "module", "exports", "process", output)((name: string) => {
    if (name === "@sentry/nextjs/config") return { withSentryConfig: (config: NextConfig) => config };
    if (name.startsWith(".")) return requireApp(path.resolve(app, name));
    return requireApp(name);
  }, mod, mod.exports, { cwd: () => app, env: {} });
  assert.equal(typeof mod.exports.default.webpack, "function", "actual application exports its webpack hook");
  return mod.exports.default;
}

const bundled = requireApp("next/dist/compiled/webpack/webpack") as typeof import("next/dist/compiled/webpack/webpack");
bundled.init();
function filesystem(cache: webpack.Configuration["cache"]): FilesystemCache {
  assert(cache && typeof cache === "object" && cache.type === "filesystem", "custom server keeps filesystem cache");
  return cache;
}
function normalized(config: webpack.Configuration): FilesystemCache {
  const options = bundled.webpack.config.getNormalizedWebpackOptions(config);
  bundled.webpack.config.applyWebpackOptionsDefaults(options);
  return filesystem(options.cache);
}

async function main() {
  const application = applicationConfig();
  const hook = application.webpack!;
  for (const compilerType of ["server", "edge-server"] as const) {
    let inherited: FilesystemCache | undefined;
    let inheritedContext: HookContext | undefined;
    let observed = false;
    // Next's exported defaults contain undefined optional values even though
    // its internal Complete type uses Required<>; no cache values are supplied.
    const nextConfig = {
      ...defaultConfig, ...application,
      experimental: { ...defaultConfig.experimental, ...application.experimental },
      images: { ...defaultConfig.images, ...application.images },
      configFile, configFileName: "next.config.ts",
      webpack(config, context) {
        const cache = filesystem(config.cache);
        // These values are generated by installed Next, never reconstructed in
        // a fixture. Its zero generation setting disables a second memory GC
        // cache in favor of Next's own MemoryWithGcCachePlugin.
        assert.equal(cache.maxMemoryGenerations, 0);
        assert.equal(cache.compression, "gzip");
        assert(cache.version && cache.name);
        inherited = structuredClone(cache);
        inheritedContext = context;
        const otherFields = { plugins: config.plugins, module: config.module, resolve: config.resolve, devtool: config.devtool };
        const result = hook(config, context);
        const actual = filesystem(result.cache);
        const defaults = normalized(result);
        assert.equal(defaults.maxMemoryGenerations, 0, "dev server must not regain Webpack's five-generation memory cache");
        for (const key of ["name", "version", "compression", "maxMemoryGenerations"] as const) {
          assert.equal(actual[key], inherited[key], `preserve Next filesystem cache ${key}`);
        }
        assert.equal(actual.cacheDirectory, path.join(app, ".next/cache/webpack"));
        assert.deepEqual(actual.buildDependencies?.defaultWebpack, [], "preserve Next's disabled default webpack dependency scan");
        assert.deepEqual(actual.buildDependencies?.config, inherited.buildDependencies?.config, "retain inherited configuration dependencies");
        for (const key of ["plugins", "module", "resolve", "devtool"] as const) assert.equal(result[key], otherFields[key]);
        observed = true;
        return result;
      },
    } as NextConfigComplete;
    const span = trace("verify-next-dev-cache");
    try {
      await getBaseWebpackConfig(app, {
        config: nextConfig, compilerType, dev: true, buildId: "cache-verification", encryptionKey: "cache-verification",
        entrypoints: {}, pagesDir: undefined, appDir: path.join(app, "app"),
        rewrites: { beforeFiles: [], afterFiles: [], fallback: [] }, originalRewrites: undefined, originalRedirects: undefined,
        runWebpackSpan: span, jsConfig: {}, resolvedBaseUrl: undefined, supportedBrowsers: undefined,
        previewProps: { previewModeId: "fixture", previewModeSigningKey: "fixture", previewModeEncryptionKey: "fixture" },
      });
    } finally { span.stop(); }
    assert(observed && inherited && inheritedContext, "installed Next calls the actual application hook");

    // A preceding tool may contribute dependency lists. They must survive the
    // application hook along with Next's filesystem cache, without duplicates.
    const priorDependency = path.join(app, "package.json");
    const cache: FilesystemCache = {
      ...inherited,
      buildDependencies: { ...inherited.buildDependencies, config: [priorDependency], additionalTool: [priorDependency] },
    };
    const input: webpack.Configuration = { mode: "development", name: compilerType, context: app, cache };
    const context: HookContext = { ...inheritedContext, dev: true, isServer: true };
    const result = hook(input, context);
    assert.deepEqual(filesystem(result.cache).buildDependencies?.additionalTool, [priorDependency], "retain other tool's dependency keys");
    assert.deepEqual(filesystem(result.cache).buildDependencies?.config, [priorDependency, configFile], "retain prior config dependencies and add the actual config");
    assert.equal(normalized(result).maxMemoryGenerations, 0);

    for (const scope of [{ dev: true, isServer: false }, { dev: false, isServer: true }, { dev: false, isServer: false }]) {
      const untouched: webpack.Configuration = { mode: "development", context: app, cache: structuredClone(inherited) };
      const originalCache = untouched.cache;
      assert.equal(hook(untouched, { ...context, ...scope }), untouched);
      assert.equal(untouched.cache, originalCache, "client/production cache is untouched");
    }
    const absent: webpack.Configuration = { mode: "development", context: app, cache: false };
    const required = filesystem(hook(absent, context).cache);
    assert.equal(required.cacheDirectory, path.join(app, ".next/cache/webpack"), "dev custom server still requires filesystem output cache");
    assert(required.buildDependencies?.config?.includes(configFile));
  }
  console.log("PASS next dev cache: actual Next node/edge defaults retained, dependencies merged, client/production unchanged; no server/compiler/provider calls");
}

main().catch(error => { console.error(error); process.exitCode = 1; });
