import assert from "node:assert/strict";
import { isCheckoutPlanId, PLAN_CATALOG } from "../../lib/billing/catalog";
import { parseEcbReferenceRates, convertUsdOffer } from "../../lib/billing/exchangeRate";
import { createPriceQuote, readPriceQuote } from "../../lib/billing/priceQuote";
import { razorpayOffer } from "../../lib/billing/razorpayProtocol";

assert.equal(PLAN_CATALOG.plus.priceUsdPerMonth, 29);
assert(isCheckoutPlanId("plus"));
assert(!isCheckoutPlanId("pro"), "retired Pro cannot be purchased by calling the API directly");
const xml = "<Cube><Cube time='2026-10-01'><Cube currency='USD' rate='1.2'/><Cube currency='INR' rate='114'/></Cube></Cube>";
const fx = parseEcbReferenceRates(xml, Date.parse("2026-10-02T12:00:00Z"));
assert.equal(fx.usdToInr, 95);
const offer = convertUsdOffer(razorpayOffer("plus"), fx);
assert.deepEqual(offer, { planId: "plus", amount: 275500, currency: "INR", usageMillicents: 12000 });
assert.equal(convertUsdOffer(razorpayOffer("lesson_top_up"), fx).amount, 95000);
assert.throws(() => parseEcbReferenceRates(xml, Date.parse("2026-10-12T00:00:00Z")), /stale/);
assert.throws(() => parseEcbReferenceRates(xml.replace("114", "0"), Date.parse("2026-10-02T00:00:00Z")));
assert.throws(() => parseEcbReferenceRates(xml.replace("2026-10-01", "2026-11-01"), Date.parse("2026-10-02T00:00:00Z")));
const secret = "quote-test-secret";
const now = Date.parse("2026-10-02T12:00:00Z");
const quote = createPriceQuote(offer, secret, now);
assert.deepEqual(readPriceQuote(quote, "plus", secret, now + 1000), offer);
assert.throws(() => readPriceQuote(quote, "lesson_top_up", secret, now), /price_changed/);
assert.throws(() => readPriceQuote(quote, "plus", "wrong-secret", now), /quote/);
assert.throws(() => readPriceQuote(quote, "plus", secret, now + 31 * 60_000), /price_changed/);
const [payload, signature] = quote.split(".");
const tampered = JSON.parse(Buffer.from(payload, "base64url").toString()) as { amount: number };
tampered.amount = 1;
assert.throws(() => readPriceQuote(`${Buffer.from(JSON.stringify(tampered)).toString("base64url")}.${signature}`, "plus", secret, now), /quote/);
console.log("✓ Single $29 plan, ECB conversion, unavailable/stale FX, tamper-proof currency quotes, and expiry");
