import assert from "node:assert/strict";
import {readFileSync,readdirSync} from "node:fs";
import {resolve} from "node:path";
import * as engine from "@heytutor/scene-engine";
import {liveSceneSaveFailure} from "../../lib/scene/sceneSaveAdmission";
import {canonicalizeTurnSceneMetadata} from "../../lib/scene/turnScenePersistence";
import {sourceCheckedStoredTurn} from "../../lib/scene/storedSceneSource";
import {restoreVerifiedPresentationFromTurn} from "../../features/tutor-session/lib/scene/restoreVerifiedDiagram";
import type {StoredTurn} from "../../lib/boards/boardsClient";
async function main(){
 assert.ok(process.argv[2],"pass the owned authored input directory generated by verify-w2-optics-numeric");
 let checks=0;
 for(const file of readdirSync(process.argv[2]).filter(row=>row.endsWith(".json"))){
  const {question,problem,plan}=JSON.parse(readFileSync(resolve(process.argv[2],file),"utf8")) as {question:string;problem:engine.ProblemIR;plan:engine.TurnPlanV3};
  const scene=engine.synthesizeFamilyScene({question,turnPlan:plan,problemIR:problem});assert.ok(scene,file);
  const solver=await new engine.LocalDeterministicSolverProvider().solve(problem),audit=engine.verifyTurnPlanAgainstSolver(problem,solver,plan,question);assert.equal(audit.status,"verified");
  const artifacts:engine.SceneArtifactsV3={schemaVersion:"scene-artifacts/v3",turnPlan:plan,problemIR:problem,solverResult:solver,solverAuthority:audit,representationTier:scene.tier,nonMetric:scene.nonMetric,candidates:[],selectedCandidateId:null,selectionReason:scene.reason,diagramResultStatus:"ready",proofObligations:[],budgets:{deadlineMs:120000,planMs:0,candidatesMs:0}};
  assert.equal(liveSceneSaveFailure({document:scene.document,question,turnPlan:plan,problemIR:problem,tier:scene.tier}),null);
  const saved=await canonicalizeTurnSceneMetadata({question,sceneDocument:scene.document,sceneArtifacts:artifacts,visualStatus:"validated",segments:[]});assert.ok(saved.ok,saved.ok?"":saved.error);
  const turn:StoredTurn={id:"offline",question,rawResponse:"",orderIndex:0,speedMultiplier:2,traceId:null,segments:[],sceneDocument:scene.document,sceneArtifacts:artifacts,visualStatus:"validated",sceneEngineVersion:null,validationReport:null};
  assert.equal(sourceCheckedStoredTurn(turn).visualStatus,"validated");assert.ok(restoreVerifiedPresentationFromTurn(turn));checks++;
  for(const defect of ["wrong-sign","wrong-unknown-unit","invented-answer","invented-unknown"] as const){
   const badPlan=structuredClone(plan);
   if(defect==="wrong-sign") badPlan.derived[0]!.value *= -1;
   if(defect==="wrong-unknown-unit") badPlan.unknowns[0]!.unit="V";
   if(defect==="invented-answer") badPlan.derived.push({id:"inventedSpeed",symbol:"speed",value:999,unit:"m/s",provenance:"derived"});
   if(defect==="invented-unknown") badPlan.unknowns.push({id:"inventedSpeed",symbol:"speed",unit:"m/s"});
   assert.ok(liveSceneSaveFailure({document:scene.document,question,turnPlan:badPlan,problemIR:problem,tier:scene.tier}),defect);
   const badArtifacts={...artifacts,turnPlan:badPlan};
   assert.equal((await canonicalizeTurnSceneMetadata({question,sceneDocument:scene.document,sceneArtifacts:badArtifacts,visualStatus:"validated",segments:[]})).ok,false,defect);
   const badTurn={...turn,sceneArtifacts:badArtifacts};assert.equal(sourceCheckedStoredTurn(badTurn).visualStatus,"retry_required",defect);assert.equal(restoreVerifiedPresentationFromTurn(badTurn),null,defect);checks++;
  }
  for(const defect of ["given","formula","unit","requested-id","quantity","reveal"] as const){
   const badIR:engine.ProblemIR=structuredClone(problem),badDoc:engine.SceneDocument=structuredClone(scene.document);
   if(defect==="given") badIR.expressions[0]!.root={kind:"number",value:99};
   if(defect==="formula") badIR.expressions[2]!.root={kind:"number",value:badDoc.quantities.find(row=>row.id==="imageResult")!.value as number};
   if(defect==="unit") badIR.solveRequests[0]!.resultBinding!.unit="V";
   if(defect==="requested-id") badIR.solveRequests[0]!.resultBinding!.turnPlanQuantityId="foreignResult";
   if(defect==="quantity") badDoc.quantities.find(row=>row.id==="imageResult")!.value=99;
   if(defect==="reveal") badDoc.revealGroups[0]!.entityIds.pop();
   assert.ok(liveSceneSaveFailure({document:badDoc,question,turnPlan:plan,problemIR:badIR,tier:scene.tier}),defect);
   const badArtifacts={...artifacts,problemIR:badIR};
   assert.equal((await canonicalizeTurnSceneMetadata({question,sceneDocument:badDoc,sceneArtifacts:badArtifacts,visualStatus:"validated",segments:[]})).ok,false,defect);
   const badTurn={...turn,sceneDocument:badDoc,sceneArtifacts:badArtifacts};assert.equal(sourceCheckedStoredTurn(badTurn).visualStatus,"retry_required",defect);assert.equal(restoreVerifiedPresentationFromTurn(badTurn),null,defect);checks++;
  }
 }
 console.log(`PASS ${checks} authored numeric whole-IR optical offline persistence/source controls; student evidence pending`);
}
main().catch(error=>{console.error(error);process.exitCode=1;});
