import assert from "node:assert/strict";
import { NextRequest } from "next/server";
import { middleware } from "../../middleware";

async function main() {
  const a = await middleware(new NextRequest("https://app.accelute.co/login", { headers: { "x-nonce": "attacker-value" } }));
  const b = await middleware(new NextRequest("https://app.accelute.co/login"));
  const csp = a.headers.get("content-security-policy") ?? "";
  const nonce = /'nonce-([^']+)'/.exec(csp)?.[1];
  assert(nonce && nonce !== "attacker-value", "nonce must be generated by the server");
  assert(!csp.split(";").find(item => item.trim().startsWith("script-src"))?.includes("unsafe-inline"), "production inline scripts need an unpredictable nonce");
  assert.notEqual(csp, b.headers.get("content-security-policy"), "each response needs its own nonce");
  assert.equal(a.headers.get("x-middleware-request-x-nonce"), nonce, "Next rendering must receive the matching nonce");
  assert.equal(a.headers.get("x-middleware-request-content-security-policy"), csp);
  console.log("CSP nonce checks passed (4)");
}
void main().catch(error => { console.error(error); process.exitCode = 1; });
