import { readScrewGaugeQuestion, SCREW_GAUGE_QUESTION_GUIDANCE, type ExpressionNodeIR } from "@heytutor/scene-engine";

export function measurementPlanningGuidance(question: string): string {
  const source = readScrewGaugeQuestion(question);
  if (source.status !== "ok") return "";
  const n = (value: number): ExpressionNodeIR => ({ kind: "number", value });
  const observed: ExpressionNodeIR = { kind: "binary", operator: "+", left: n(source.values.true_reading.value), right: n(source.values.zero_error.value) };
  const requested: ExpressionNodeIR = { kind: "binary", operator: "/", left: { kind: "binary", operator: "-", left: observed, right: n(source.values.main_scale_reading.value) }, right: n(source.values.least_count.value) };
  return `\n${SCREW_GAUGE_QUESTION_GUIDANCE}\nMEASUREMENT SOURCE DATA\n${JSON.stringify({values:source.values,evidence:source.evidence,observedAST:observed,requestedCountAST:requested,quantityId:"circular_reading",symbol:"circular_reading",unit:"division",factStatements:{pitch:"pitch",least_count:"least count",true_reading:"wire diameter",zero_error:"zero error",circular_reading:"circular scale divisions"}})}\n
This complete source requests only a scalar circular-scale count, not a drawing: use visualRequirement=none, no qualitativeClaims and no assumptions. A verified instrument figure is unsupported for this profile. Do not append a diagram request or invent scale geometry. Use the signed zero error exactly as supplied: observed=true diameter+signed zero error, not subtraction of the signed error. Source data supplies the independently recomputed count; option answers are not evidence. Use the supplied quantityId, symbol and unit for BOTH the unknown and derived row and the original IR resultBinding, even when the Plan is not yet available. Given IDs are p, LC, d and e0. Fact statements are EXACTLY the supplied factStatements strings, without a parenthesized symbol, prefix, signed adjective or calculation. The derived sourceText is ONLY the five exact fact quotes joined by ' | '; do not append an equation, worked calculation, prose or delimiter. Arithmetic lives in the complete IR AST and later teaching, not in this evidence field. Omit sign when unsure; a sign must otherwise be positive, negative or zero, never + or -. In ProblemIR emit the supplied complete typed requestedCountAST as root; omit compact expr. A negative numeric value must be a number node, not a unary rewrite or rounded string. Match the exact evidence and actual Plan identities specified above. Retain every returned field and obligation for independent whole-IR audit; this data never substitutes for the model's original returned graph.\n`;
}
